### ISSUE TITLE
windows VSS and verify issue

### ISSUE THREAD

**Issue by gitboogey** [fcorbelli/zpaqfranz#102]
Hi,

I am using zpaqfranz (v59.3) on windows, with the -vss and -verify flags (in an elvated powershell window). 
When using it, the shadow copy is created, then the achiving is done, and the the shadow copy is deleted. Its all fine. 

My problem is, that the verify step is done by comparing with the live filesystem, which can be changed during the archiving time, like in the user's profile directory (which is one of my use cases).  
So the tool validly reports that some files were chaned ("STORED HASH EA19780EF5C43DF9 VS 635656EC9CC02201 IN FILE ..."). 

I think that there is a logical error, becase the verifying should be done against the state in the shadow copy, and not against a filesystem, where we know, that there will be changes, and becuse of this errors. 

I suggest to change in this case the working to the following sequence: 
create shadow copy, do the archiving, verify against the shadow copy, delete the shadow copy. 

What do you think about it? 

Best regards.

**Comment by fcorbelli** [comment]
Thank you for the report, but I'm afraid you are using the wrong command for what you want to do

The **verify** command works to remotely check (or after an extraction) the hashes of files, OR that nothing is changed during the backup (but with VSS this is normal, then -verify doest not have sense)

If you want to do a "double check" the command to use (and the corresponding switch) is **test**

But "-test" and "-vss" are incompatible
You cannot test a -vss by reading again from filesystem, because something can (should/must) be different

I see your point, I'll think about a two-stage run
First the add, then the test, then the release of the VSS

**Comment by fcorbelli** [comment]
Please try (pre-release 59.7c)
```
zpaqfranz update -force
```
then
```
zpaqfranz a z:\test.zpaq c:\users -vss -test
```

**Comment by fcorbelli** [comment]
OK, 59.7f pre-release is uploaded
(zpaqfranz update -force)

Should handle -test and -verify and even -test AND -verify AND even -ssd

**Comment by gitboogey** [comment]
Hi, 

thank you for the new version, which I  tested a little bit. It seem to do a requested thing with -vss & -test/-verify.
I found something disturbing: although the checks seems to find no errors, there is some difference reported: 

zpaqfranz v59.7f-JIT-GUI-L,HW BLAKE3,SHA1/2,SFX64 v55.1,(2024-05-23)
franz:-xxhash -noconsole -noeta -test -verbose -vss
24/05/2024 22:17:39 VSS: starting
24/05/2024 22:17:41 VSS: end
Integrity check type: XXHASH64+CRC-32
Creating prof_12.zpqf at offset 0 + 0
Add 2024-05-24 22:17:39     2.485      1.786.539.893 (   1.66 GB) 4T (209 dirs): -m14
Non-latin (UTF-8)             5
MAX_FRAGMENT 520.192 (507.94 KB)
2.694 +added, 0 -removed.
                    0 starting size
        1.786.539.893 data to be added
        1.690.840.151 after deduplication
          710.570.663 after compression
          710.570.663 total size
Total speed 20.46 MB/s
IO buffer 1.048.576

**-test on VSS**
Compare archive content of:
prof_12.zpqf:
1 vers, 2.694 files, 23.253 frags, 148 blks, 710.570.663 bytes (677.65 MB)

2.694 in <<//?/GLOBALROOT/Device/HarddiskVolumeShadowCopy14/Users/xxxxxx/AppData/Roaming/Thunderbird/Profiles/>>
Total files found: 2.694

**00002694 = same
Total different file size: 0 bytes**
24/05/2024 22:19:29 VSS: starting release
24/05/2024 22:19:30 VSS: end releasing

**HOUSTON expected 1.786.539.893, done 1.787.130.149, diff 590.256**
This could be 'normal' for a VSS operation
**no file errors tracked**
110.277 seconds (00:01:50) **(with errors)**

2, 

zpaqfranz v59.7f-JIT-GUI-L,HW BLAKE3,SHA1/2,SFX64 v55.1,(2024-05-23)
franz:-xxhash -noconsole -noeta -verbose -verify -vss
24/05/2024 22:20:56 VSS: starting
24/05/2024 22:20:58 VSS: end
Integrity check type: XXHASH64+CRC-32 + CRC-32 by fragments
Creating prof_22.zpqf at offset 0 + 0
Add 2024-05-24 22:20:56     2.485      1.786.539.893 (   1.66 GB) 4T (209 dirs): -m14
Non-latin (UTF-8)             5
MAX_FRAGMENT 520.192 (507.94 KB)
2.694 +added, 0 -removed.
                    0 starting size
        1.786.539.893 data to be added
        1.690.840.151 after deduplication
          710.570.663 after compression
          710.570.663 total size
Total speed 19.07 MB/s
IO buffer 1.048.576

**-verify on VSS**

prof_22.zpqf:
1 vers, 2.694 files, 23.253 frags, 148 blks, 710.570.663 bytes (677.65 MB)

Verify hashes of one version vs filesystem (1 thread, -ssd for multithread)
Scan done, preparing report...

**OK       XXHASH64 : 00002441 of 00002441 (     1.66 GB hash check against file on disk)**

Total hashed bytes 1.787.130.149 @ 72.597.398 B/s
24/05/2024 22:22:51 VSS: starting release
24/05/2024 22:22:51 VSS: end releasing

**HOUSTON expected 1.786.539.893, done 1.787.130.149, diff 590.256**
This could be 'normal' for a VSS operation
**no file errors tracked**
114.801 seconds (00:01:54) **(with errors)**

Can you explain, where these diffs and errors come from? 
I found it interesting that in different runs I got the same diff numbers...

Btw can I request to implement the -noeta feature to the  "t" (test) comand? In the logs (created by redirection) it is very annnoying. 

Thank you in advance.

**Comment by fcorbelli** [comment]
>Can you explain, where these diffs and errors come from?
>I found it interesting that in different runs I got the same diff numbers...

The difference is what there is between the beginning of the copy, and the end. Essentially, during the data scanning phase, not only the file names are recorded, but also the size of the files. Then the compression phase begins, which can take quite some time. During this time the files may change size or not be accessible at all (why? Who can tell? It should not happen, especially with VSS, but it does happen). So zpaqfranz starts out expecting, say, to have to process 1,000,000 bytes, however, it actually processes 1,000,035 bytes (because the sum of the files read has that size). So here, in the example, is the difference of 35 bytes. I could probably implement a more accurate report, with the individual files whose size varies. It would take up a little extra RAM



>Btw can I request to implement the -noeta feature to the "t" (test) comand? In the logs (created by >redirection) it is very annnoying.

This should be already here. Can you please post a command line example, so I can fix?
Thank you

**Comment by fcorbelli** [comment]
Just uploaded pre-release 59.7h

> (in an elvated powershell window).

Running on non-admin shell try a runhigh() (not _really smart_, but should work on common scenarios)

**Comment by gitboogey** [comment]
Hi, 

1, -noeta with test: works, is ok. It is only missing from the help (... h t).

2, testing -vss  I have not seen any improvement, there are some time these 
"HOUSTON expected 1.786.712.866, done 1.788.129.077, diff 1.416.211
This could be 'normal' for a VSS operation"
and some time not. 
I found some information that says that the shadow copy creation command finishes instantly, but it will take windows some time to create a shadow copy in the background. So to be safe before using it, it's state should be checked. See also https://learn.microsoft.com/en-us/previous-versions/windows/desktop/vsswmi/win32-shadowcopy 


3, I found, that some combinations with -verbose like 
zpaqfranz_v59.7k.exe a prof_51.zpqf C:\Users -xxhash  -test -verbose 
and 
zpaqfranz_v59.7k.exe a prof_7.zpqf C:\Users -xxhash -vss -test -verbose
have in the eta output some empty lines, It seems to me, that there are somewhere unnecessary newlines printed. 

4, checking the contents of the archives with the list command I found, that when using the -vss switch then the "base" folder is not added to the archive, but without it is is added. I think it should be the same. 
zpaqfranz_v59.7k.exe a prof_5.zpqf C:\Users -xxhash  -test
prof_5.zpqf contains "C:/Users/"
but 
zpaqfranz_v59.7k.exe a prof_1.zpqf C:\Users -xxhash -vss -test 
prof_1.zpqf does not.

Best regards.

**Comment by fcorbelli** [comment]
(2) no improvement, but with -verbose you should see what files are different
(3) this seems a bug (BTW -xxhash is useless, it is the default)
(4) vss works in very strange and unknown ways, I'll check

>  So to be safe before using it, it's state should be checked

Handling vss is very painful: documentation almost absent, old, not working etc. No promises, I typically use zfs snapshots, not vss

Thanks for the report, really helpful

**Comment by gitboogey** [comment]
Hi,

I found another issue regarding VSS. I figured out, that for handling the shadow copies batch files (in the temp folder) are used. By examining the batch files, I have seen, that the command "wmic shadowcopy delete /nointeractive" is used before the creation and also for deleting it after the archiving. I think it is used for easy identification of the shadow copy to be used (because only one should be there at this time).

I have more problems with this approach:
1, All not related shadow copies are deleted, with the possibility of causing unintended harm, because we do not know, why they are there. (It can be an unrelated snapshot, restore point etc. )
2, Because of this some antivirus / EDR solutions can flag his command as unwanted behavior (there are ransomwares, which use this technique), and quarantine the application, making it unusable.

I suggest to use another way to create and delete the shadow copies - using powershell scripting.

The following lines can be put into a batch file, and called as the shadow copy creation script:

```
@echo OFF
@powershell -command "$vscc= (Get-WmiObject -List Win32_ShadowCopy).Create("""C:\\""", """ClientAccessible"""); $vsci = Get-WmiObject Win32_ShadowCopy | Where-Object { $_.ID -eq $vscc.ShadowID }; Set-Content -Path $env:temp\zpqfvssID.txt -Value $($vsci.ID); Set-Content -Path $env:temp\zpqfvssDQ.txt -Value $($vsci.DeviceObject); Set-Content -Path $env:temp\zpqfvssVN.txt -Value $($vsci.VolumeName); $batcmd="""@echo OFF`r`n@vssadmin delete shadows /Shadow="""+$($vsci.ID)+""" /Quiet"""; Set-Content -Path $env:temp\zpqfvssDEL.cmd -Value $batcmd"

```
This script does not delete the existing copies, creates some temp files with some shadow copy properties for further processing, and creates even a dedicated shadow copy delete script (zpqfvssDEL.cmd). It can be generated/tweaked according zpaqfranz's needs, and I think it is a good foundation.

Please adapt and use it.

Thank you in advance.

**Comment by fcorbelli** [comment]
>1, All not related shadow copies are deleted

I really do not care :) I am too lazy to  make a "good" parser. During debug a lot of dangling VSS snapshots will remain

>2, Because of this some antivirus / EDR solutions can flag ...

I really do not care, either :) (powershell can be stopped just like a script)

The real problem is the state
The VSS remain in state=12 without becoming state=16

Why? I do not know

**Comment by fcorbelli** [comment]
PS ClientAccessibile does not seems the "good" type of VSS
And managing VSS via gcc is really, really, REALLY complex, involving a mixed configuration with M$ stuff. Effort too big

**Comment by fcorbelli** [comment]
THIS is the problem

```
>> Get-WmiObject -Query "SELECT * FROM Win32_ShadowCopy" | Select-Object ID, DeviceObject, InstallDate, State

ID                                     DeviceObject                                    InstallDate               State
--                                     ------------                                    -----------               -----
{4B26569A-3C94-4DB3-A161-445AFDB0A719} \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy4 20240531130959.884752+120    12
```
