### ISSUE TITLE
integrating with other software 

### ISSUE THREAD

**Issue by chaosdrop** [fcorbelli/zpaqfranz#103]
Hi, I use zpaqfranz for some personal archiving, and think it's pretty amazing. I tried asking a couple of the companies who make universal compression handlers like Bandizip if they would consider adding Zpaqfranz support since they have Zpaq support and got the reply:

```
I'm sorry to say that we don't have a plan to apply the source.

zpaqfranz is not designed to be used as a library, and other software will not want to use it.
```

I thought I'd share this information since it seems a shame that zpaqfranz isn't being used in other software despite being one of the best compression options available.

**Comment by fcorbelli** [comment]
Thanks for the report
I never thought of maintaining any library interface, mine is a tiny little known project
If I had more users, and thus feedback etc, certainly I could do it

**Comment by fcorbelli** [comment]
If you refer to "this" zpipe https://encode.su/threads/472-Introducing-zpipe-a-streaming-ZPAQ-compatible-compressor it is way obsolete against zpaqfranz

Which can use -stdin and -stdout even on versioned archives (!)
You can use zpaqfranz, for example, to "catch" mysqldump
Or dd
Of zfs send
And you can (with the lost of deduplication) make special-ordered archives, to extract with -stdout to mysql, or dd, or zfs receive
😄
