### ISSUE TITLE
Trim command not working on multi part archive?

### ISSUE THREAD

**Issue by Namke** [fcorbelli/zpaqfranz#107]
I just tried to trim some incomplete archive out of one multi part archive. However it always spawn "so sorry, this seems a multipart archive, abort" then quit. Does trim command currently not support multi part archive and does it gonna support in near future?

**Comment by fcorbelli** [comment]
Trim does not support multi part archive and will not support anytime soon
Because you can directly delete the last part of the archive (with the incomplete transaction)
That's all

> TRIM works with ONLY one single .zpaq file (no multipart)

**Comment by Namke** [comment]
Yes manual is one of solution. But generally incomplete transaction could happen without knowing (daily backup let say).
And pretty complex to determined which is broken batch (its not always last file but last batch of files, correct?), so I guess automatic cleanup is necessary. In this case is decided which batch of file is contain incomplete transaction, clean it.

**Comment by fcorbelli** [comment]
In reality it essentially never happens, except by “treacherous” process interruption (if you press control-C it is intercepted and the last piece deleted). Deleting an incomplete transaction, in a sequence of files, is complex and fragile; there is no concept of a “chunk” in zpaq
Usually my advice is to use the backup (and testbackup) command in the case of multi-archives
