### ISSUE TITLE
Respect NO_COLOR

### ISSUE THREAD

**Issue by dertuxmalwieder** [fcorbelli/zpaqfranz#108]
I *do* use an "*ix shell" (namely, `rc`), but as I *hate* a shell that looks like an unicorn had puked all over it, I usually use [NO_COLOR](https://no-color.org) to get rid of that. zpaqfranz - now that it supports colors - should respect that.

**Comment by fcorbelli** [comment]
Sadly, there is
But only for... Windows 😄 
```
#ifdef _WIN32
	char *no_color=getenv("NO_COLOR");
	if ((no_color!=NULL) && (no_color[0]!='\0'))
		flagnocolor=true;

```
I'll fix

PS what do you think of the new list format? Do you like it?

**Comment by dertuxmalwieder** [comment]
Nobody uses NO_COLOR on Windows! ;-)

Ah, my personal taste is not relevant, I guess.

**Comment by fcorbelli** [comment]
> Nobody uses NO_COLOR on Windows! ;-)
> 
> Ah, my personal taste is not relevant, I guess.

Why not? Kaizen matters

**Comment by dertuxmalwieder** [comment]
Sure, but it’s your tool, not mine. I - personally - wouldn’t even have added `dir`.
