### ISSUE TITLE
Problem in exporting and viewing

### ISSUE THREAD

**Issue by adamantida** [fcorbelli/zpaqfranz#110]
Hi, after a couple of updates the "x" and "l" stopped working
![image](https://github.com/fcorbelli/zpaqfranz/assets/43584533/46cd97c8-841a-4399-a900-701e9e43a0a3)

**Comment by fcorbelli** [comment]
please try using -attr switch

**Comment by adamantida** [comment]
> please try using -attr switch

![image](https://github.com/fcorbelli/zpaqfranz/assets/43584533/aa69572a-82a4-4bc7-9217-da35184735b7)

**Comment by adamantida** [comment]
если использовать -715, то всё работает
![image](https://github.com/fcorbelli/zpaqfranz/assets/43584533/aa08b1c1-5321-4de2-b240-d196c0b0ab8d)
![image](https://github.com/fcorbelli/zpaqfranz/assets/43584533/8b106f79-b738-44b2-be49-7a37084933c1)

**Comment by fcorbelli** [comment]
Can you please make a
```
zpaqfranz upgrade -force
```
?
This will update to 59.9b (pre-release)
Thank you

**Comment by fcorbelli** [comment]
Please try the pre-release 59.9b, running a 
```
zpaqfranz upgrade -force
```

**Comment by adamantida** [comment]
> Please try the pre-release 59.9b, running a
> 
> ```
> zpaqfranz upgrade -force
> ```

![image](https://github.com/fcorbelli/zpaqfranz/assets/43584533/e14eaf9e-8f79-41f3-a7e7-359aec8d58cf)
Yep, its work
