### ISSUE TITLE
bug with -all

### ISSUE THREAD

**Issue by adamantida** [fcorbelli/zpaqfranz#111]
![image](https://github.com/fcorbelli/zpaqfranz/assets/43584533/f3d87587-8e6c-4b2b-a0e4-a3f5b4fdb974)

**Comment by fcorbelli** [comment]
???

**Comment by adamantida** [comment]
> ???
-all doesn't show all files in all versions. 
I think the video will tell a little more.
https://youtu.be/3N-ZChLBi8A

**Comment by adamantida** [comment]
While recording the video, I saw another bug. With updating the archive, after deleting a file. Same bug with -715 as well. I'd be a freak if I didn't download a regular zpaq to check this, and it works fine there (although it worked fine in previous versions before -update).

In the end, it's not just "-all" anymore

**Comment by fcorbelli** [comment]
You are using the -ads switch, that is not aligned with the new list command.
You can enforce a -ads (in the list command) to turn off

**Comment by fcorbelli** [comment]
> While recording the video, I saw another bug. With updating the archive, after deleting a file. Same bug with -715 as well. I'd be a freak if I didn't download a regular zpaq to check this, and it works fine there (although it worked fine in previous versions before -update).
> 
> In the end, it's not just "-all" anymore

???

**Comment by fcorbelli** [comment]
OK, maybe I understand.

You prefer a behavior more like zpaq, which creates a new version in case there are only deleted files.
I just uploaded (to the upgrade channel) pre-release 59.10b which does this

Regarding -ads, on the other hand, to show individual versions rather than all of them, I don't think I will work on that. It is very complex and slow
I will refine instead, perhaps, the self-alignment

**Comment by adamantida** [comment]
> > While recording the video, I saw another bug. With updating the archive, after deleting a file. Same bug with -715 as well. I'd be a freak if I didn't download a regular zpaq to check this, and it works fine there (although it worked fine in previous versions before -update).
> > In the end, it's not just "-all" anymore
> 
> ???

In the video, after deleting a file - you cannot update the archive unless some other file is updated. It's in the video. I don't quite understand the "?????"

>> You prefer a behavior more like zpaq, which creates a new version in case there are only deleted files.
I just uploaded (to the upgrade channel) pre-release 59.10b which does this

 - yep, This error looked strange to me, that's why I said that maybe it is. So I checked it with a regular zpaq

**Comment by adamantida** [comment]
> You prefer a behavior more like zpaq, which creates a new version in case there are only deleted files.
> I just uploaded (to the upgrade channel) pre-release 59.10b which does this

thx

**Comment by fcorbelli** [comment]
I uploaded pre-release 59.10c, that does write in yellow... deleted file
I hope this should be plus clear
![deleted](https://github.com/fcorbelli/zpaqfranz/assets/77727889/3f3f90a8-d9c2-4a4d-9aef-4309c895ba7c)

Do you like? Any other (very welcome) suggestions?

**Comment by adamantida** [comment]
> I uploaded pre-release 59.10c, that does write in yellow... deleted file I hope this should be plus clear ![deleted](https://private-user-images.githubusercontent.com/77727889/342505028-3f3f90a8-d9c2-4a4d-9aef-4309c895ba7c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNjYxNzQsIm5iZiI6MTcxOTI2NTg3NCwicGF0aCI6Ii83NzcyNzg4OS8zNDI1MDUwMjgtM2YzZjkwYTgtZDljMi00YTRkLTlhZWYtNDMwOWM4OTViYTdjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDIxNTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMzdmNDdkYjYyZWY4YjJiMDI1Y2Y2ZGE4NDdmMTdmYWY0ZDJiZmY5MGVkMjljZDNkZjIxOGIyYmVhYjUzMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j-j2A36s4wGgHW76NO9YacFMC_2cko8N0P5-moYsfTA)
> 
> Do you like? Any other (very welcome) suggestions?

Yep, I like that it is now visible when updating. It would also be great if deleted files were highlighted with a minus when both add(+) and delete(-) goes. But it's not necessary 😄

**Comment by fcorbelli** [comment]
> > > While recording the video, I saw another bug. With updating the archive, after deleting a file. Same bug with -715 as well. I'd be a freak if I didn't download a regular zpaq to check this, and it works fine there (although it worked fine in previous versions before -update).
> > > In the end, it's not just "-all" anymore
> > 
> > 
> > ???
> 
> In the video, after deleting a file - you cannot update the archive unless some other file is updated. It's in the video. I don't quite understand the "???"
> 
> > > You prefer a behavior more like zpaq, which creates a new version in case there are only deleted files.
> > > I just uploaded (to the upgrade channel) pre-release 59.10b which does this
> 
> * yep, This error looked strange to me, that's why I said that maybe it is. So I checked it with a regular zpaq

Yes, you can (even with <59.10b), with a -force switch in add

I know... I know... I like switches too much 😄 

Effectively it is a (default) different behavior from zpaq, and therefore it is appropriate to make it more similar

**Comment by adamantida** [comment]
But basically, if they're already highlighted in yellow, it's not necessary. But I think people who use No-Color will find it convenient

**Comment by adamantida** [comment]
> Effectively it is a (default) different behavior from zpaq, and therefore it is appropriate to make it more similar

Most importantly, please write that when using -ads you should write it in "l" as well, because it was not required before

**Comment by fcorbelli** [comment]
> But basically, if they're already highlighted in yellow, it's not necessary. But I think people who use No-Color will find it convenient

![a](https://github.com/fcorbelli/zpaqfranz/assets/77727889/81cc150a-a350-4af3-9f99-d1d2f2228fa9)
![b](https://github.com/fcorbelli/zpaqfranz/assets/77727889/57f9d2bc-4cbc-4c4e-8e71-fe5b7de107df)

On ADS: sooner or later I'll perfect it

**Comment by adamantida** [comment]
> > But basically, if they're already highlighted in yellow, it's not necessary. But I think people who use No-Color will find it convenient
> 
> ![a](https://private-user-images.githubusercontent.com/77727889/342507779-81cc150a-a350-4af3-9f99-d1d2f2228fa9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNjcxOTUsIm5iZiI6MTcxOTI2Njg5NSwicGF0aCI6Ii83NzcyNzg4OS8zNDI1MDc3NzktODFjYzE1MGEtYTM1MC00YWYzLTlmOTktZDFkMmYyMjI4ZmE5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDIyMDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYWM0MzY2NDcwYTFlMjlkZDdlNDRlN2VjNGZiMjgxYjgzYjhiNzk4ZDM0NTExMWMwODdiMTE5Y2Y0NTVlZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zv14utBpesV4qiO0mgtj25bbxckgx3h-fIOVBsXpymA) ![b](https://private-user-images.githubusercontent.com/77727889/342507788-57f9d2bc-4cbc-4c4e-8e71-fe5b7de107df.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNjcxOTUsIm5iZiI6MTcxOTI2Njg5NSwicGF0aCI6Ii83NzcyNzg4OS8zNDI1MDc3ODgtNTdmOWQyYmMtNGNiYy00YzRlLThlNzEtZmU1YjdkZTEwN2RmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDIyMDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZTZkMzEyZTkxMTE3YWQ4NTNkMjYzNDRkMTQzYzI0OTk1ZWY4OTExZjUwMDc3OWI2NzE1OWFmNDMwY2QyNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nqlq17wcxT6cC6RzptjChxXgYDEjBPmxCrw54YlNLoc)
> 
> On ADS: sooner or later I'll perfect it

Oh, I meant add here, not "Files: added +2 removed -1".
Discommunication has occurred 
![image](https://github.com/fcorbelli/zpaqfranz/assets/43584533/9ee66815-9a1b-46a5-bb16-8ab82eea9069)

**Comment by adamantida** [comment]
If we talk more about the visual component, then it's strange enough that the updated files are marked as added rather than "updated". Not sure about usefulness, but it's handy to see what's updated
For example:
File: added 1 removed 0 updated 2

**Comment by fcorbelli** [comment]
Because in fact they are (added) to the version. 
There are never any updates in zpaq. 
Data is only added to the file, the initial part of which remains the same. 
In multipart mode it is easier to understand: the data are added (in a new chunk)
I can't quickly find of an easy way to do this count, maybe I'll think about it

**Comment by adamantida** [comment]
> I can't quickly find of an easy way to do this count, maybe I'll think about it

To use your popular line: It's very complicated and slow

**Comment by adamantida** [comment]
Well, thank you for asking about taste preferences, if anything it will be more convenient for someone else.
I may have misspoken but come on

**Comment by fcorbelli** [comment]
> > I can't quickly find of an easy way to do this count, maybe I'll think about it
> 
> To use your popular line: It's very complicated and slow

It is REALLY complicated, because I need an extra byte, and this require a LOT of work
Counting is slow
Already done
```
DTMap::iterator p=vf[fi];
string newname=rename(p->first.c_str());
DTMap::iterator a=dt.find(newname);
if (a==dt.end() || a->second.date==0) 
files_added++;
else 
files_updated++;	
```
Maybe I can inject into the attr.
I'll think tomorrow

**Comment by fcorbelli** [comment]
This IS really very complicated and slow
It is a very first draft. You have to use it using the -binary switch during additions (in the future I will put it maybe as default)
```
zpaqfranz a z:\1.zpaq *.cpp -binary
```
It actually also stores the date the files were created and also creates smaller files (by a little). In any case, there is still work to be done
![1](https://github.com/fcorbelli/zpaqfranz/assets/77727889/611c6fad-56e4-4282-938b-4467e8201ac0)
[60_10a.zip](https://github.com/user-attachments/files/15971947/60_10a.zip)

**Comment by adamantida** [comment]
> This IS really very complicated and slow It is a very first draft. You have to use it using the -binary switch during additions (in the future I will put it maybe as default)
> 
> ```
> zpaqfranz a z:\1.zpaq *.cpp -binary
> ```
> 
> It actually also stores the date the files were created and also creates smaller files (by a little). In any case, there is still work to be done ![1](https://private-user-images.githubusercontent.com/77727889/342743015-611c6fad-56e4-4282-938b-4467e8201ac0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzQzOTQsIm5iZiI6MTcxOTMzNDA5NCwicGF0aCI6Ii83NzcyNzg4OS8zNDI3NDMwMTUtNjExYzZmYWQtNTZlNC00MjgyLTkzOGItNDQ2N2U4MjAxYWMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE2NDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YmJhNGNkMjE2ODZkNjA0YjJjOWI2ZTNlNzBiODdkYWVmMDY0MTZlZjFiZDYwZjgyNjRlM2NlM2Y4NjQ5NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vEnvuqkrnbgWiIquRi-7u08ToPThelD3qFUkEQfZb5A) [60_10a.zip](https://github.com/user-attachments/files/15971947/60_10a.zip)

It looks beautiful. But I think folders should not be labeled as "#" when they are added, it looks weird;
But as far as I'm concerned, it's cool that you can now see that files have been changed

**Comment by fcorbelli** [comment]
![dir](https://github.com/fcorbelli/zpaqfranz/assets/77727889/f2047140-59aa-483d-9aa7-f317839604e2)

**Comment by fcorbelli** [comment]
![esplodono](https://github.com/fcorbelli/zpaqfranz/assets/77727889/17bdc541-bd8a-47f6-a127-9d9ffeae99dc)

**Comment by fcorbelli** [comment]
![upz](https://github.com/fcorbelli/zpaqfranz/assets/77727889/98ddcb5a-ec5c-4545-9be4-f44f27135c1a)

**Comment by fcorbelli** [comment]
![crea2](https://github.com/fcorbelli/zpaqfranz/assets/77727889/cf102152-45d5-4c77-8eec-5002ab3b6d5a)
![creation](https://github.com/fcorbelli/zpaqfranz/assets/77727889/0e8f0ef8-1600-448f-98cf-ed7f5e7f3098)

**Comment by fcorbelli** [comment]
![fullbar](https://github.com/fcorbelli/zpaqfranz/assets/77727889/dca596e5-536d-484d-9803-a482b056c30e)
