### ISSUE TITLE
v60 build for linux?

### ISSUE THREAD

**Issue by KweezyCode** [fcorbelli/zpaqfranz#113]
title

**Comment by fcorbelli** [comment]
???

**Comment by KweezyCode** [comment]
where could i get the latest build for linux? The latest is 60, but it is not compiled (check screenshot)
![image](https://github.com/fcorbelli/zpaqfranz/assets/36813920/72eca90f-5859-4a73-8c64-e3f670c2e0e9)

**Comment by fcorbelli** [comment]
Ah, you're right, sorry, I didn't understand.
Normally, if you have a gcc or clang compiler installed, you can compile it yourself (in the source you can find instructions for major distributions)
I keep static binaries for situations where the compiler is not there (for example: the NAS)
I will update with the latest version by today

**Comment by KweezyCode** [comment]
okay, thanks!

**Comment by fcorbelli** [comment]
Please try, should work
Thank you

**Comment by KweezyCode** [comment]
![image](https://github.com/fcorbelli/zpaqfranz/assets/36813920/e2b857c0-9aef-412d-b472-f1a870440ed3)
processor       : 15
vendor_id       : AuthenticAMD
cpu family      : 25
model           : 80
model name      : AMD Ryzen 7 5700G with Radeon Graphics
stepping        : 0
microcode       : 0xa50000d
cpu MHz         : 3701.264
cache size      : 512 KB
physical id     : 0
siblings        : 16
core id         : 7
cpu cores       : 8
apicid          : 15
initial apicid  : 15
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local user_shstk clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm debug_swap
bugs            : sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass srso
bogomips        : 7603.79
TLB size        : 2560 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]

**Comment by fcorbelli** [comment]
I suggest compile the program. 
I don't use arch very often, however, you should be able to do it fairly easily

Or try
```
yay -S zpaqfranz-git
```

**Comment by KweezyCode** [comment]
okay. Should i close ticket?

**Comment by fcorbelli** [comment]
Please try the attached binary (if you want)
I made with this
```
c++ -O2 -DHWSHA2 -D_FORTIFY_SOURCE=3 -Dunix zpaqfranz.cpp -pthread -o zpaqfranz_arch -s -static
```

[60_3_arch.zip](https://github.com/user-attachments/files/16120208/60_3_arch.zip)

**Comment by 197788** [comment]
I use Archlinux also. The AUR is not as up to date. 
1. I just git cloned this project
2. I open terminal, cd inside the cloned folder
3.  I type"make" and wait. I get the output "g++ -Dunix -O3 -pthread  zpaqfranz.cpp -lm -o zpaqfranz".
4. After a little while you now have a binary file called "zpaqfranz" inside the folder now.
5. Type "./zpaqfranz". It should output the version number and some other output also. You can use it as is (you must specify where the binary is each time), or you can further install it to the filesystem (globally) with sudo make install.
6. The default is it will install to /usr/local/bin, which is fine on my Arch system. You can make manual changes to the makefile to change where it will be installed. I left it as is.
7. Now you can call zpaqfranz from anywhere in the terminal without needing to use the direct file path.

**Comment by fcorbelli** [comment]
The AUR is always up to date

For a fresh Manjaro 24.0.3 installation I suggest
```
sudo pacman -Sy
sudo pacman -S gcc (or sudo pacman -S clang)
sudo pacman -S fakeroot
sudo pacman -S yay
yay zpaqfranz
```
Answers to yay
Packages to install ==> 1
Packages to cleanBuild ==> A
Diffs to show? ==> N
Proceed with installation => y
(insert sudo password)

**Comment by 197788** [comment]
> The AUR is always up to date
> 
> For a fresh Manjaro 24.0.3 installation I suggest

Okay, thanks. I was not telling it to make a cleanBuild. It definitely worked.
