### ISSUE TITLE
Filelist breaks when multiple backups are running

### ISSUE THREAD

**Issue by sheckandar** [fcorbelli/zpaqfranz#123]
If I run multiple backups at the same time (multiple zpaqfranz processes) and have `-filelist` enabled, then whichever process exits first deletes the file in `/tmp` and then all the other processes throw an error: `/tmp/<filelist name>: No such file or directory`

The recommended way would be to create a randomly named directory for each process, IMHO.

Process 1 - `/tmp/dh1324j/<filelist name>`
Process 2 - `/tmp/hgdl33ll/<filelist name>`

Sequential folder names would also work.

**Comment by fcorbelli** [comment]
[60_6u.zip](https://github.com/user-attachments/files/16729325/60_6u.zip)
You can try this untested pre-release

**Comment by sheckandar** [comment]
Thanks. That works.

But I would suggest a clean up code for the vfile directory on exit. It will accumulate over time as the system is rarely restarted.

Leave _zpaqfranz directory but delete the "timestamp" directory.

```
ls -alh /tmp/_zpaqfranz/
total 0
drwx------  7 root root  140 Aug 24 16:00 .
drwxrwxrwt 23 root root 2.4K Aug 24 16:00 ..
drwx------  2 root root   60 Aug 24 15:56 1724536582447
drwx------  2 root root   60 Aug 24 15:56 1724536593831
drwx------  2 root root   40 Aug 24 15:56 1724536594332
drwx------  2 root root   40 Aug 24 15:59 1724536744742
drwx------  2 root root   40 Aug 24 16:00 1724536803448
```
