### ISSUE TITLE
pakka gui hash dropdown

### ISSUE THREAD

**Issue by Sanesecurity** [fcorbelli/zpaqfranz#125]
Hi,

Using the pakka gui, could the list of drop down hashes be updated.

My benchmarks are:

WHIRLPOOL:    98.04 MB/s (done   490.19 MB)
       SHA-3:   221.25 MB/s (done     1.08 GB)
     SHA-256:   231.40 MB/s (done     1.13 GB)
       SHA-1:   450.44 MB/s (done     2.20 GB)
         MD5:   529.40 MB/s (done     2.58 GB)
   HIGHWAY64:   813.60 MB/s (done     3.97 GB)
      BLAKE3:     2.03 GB/s (done    10.14 GB)
    XXHASH64:     4.06 GB/s (done    20.32 GB)
        XXH3:     4.40 GB/s (done    21.94 GB)
     CRC-32C:     4.86 GB/s (done    24.22 GB)
      WYHASH:     6.05 GB/s (done    30.17 GB)
      CRC-32:     6.14 GB/s (done    30.61 GB)
    NILSIMSA:     6.15 GB/s (done    30.67 GB)

So, would using NILSIMSA make more sense (for speed) than using the defaut pakka hash of xxhash ?

**Comment by fcorbelli** [comment]
NILSIMSA is the contrary of an hash (!)
It is a very rough measure of SIMILARITY and not of DIFFERENCE between files. It is used to identify emails that differ by only a few details (the .eml files that contain them). The goal is to determine if, in large quantities of emails (typically hundreds of thousands), there are many duplicates. This cannot be done with a 'true' hash, where even a single bit of difference results in a completely different hash value.

You cannot use NILSIMSA (or wyhash) as an internal hash for zpaqfranz. Only for the sum, hash, d (deduplicate) etc

**Comment by fcorbelli** [comment]
In your case XXHASH64 is faster than (realistically) your media
If you have (for example) an SSD capable of transferring (say) 400MB/s real-world and you use whirlpool (~100MB/s) you will get a huge slowdown
For a 4GB/s hash (vs. 400MB/s) this will be much smaller
=>
the xxhash64 is very fast even on not very powerful CPU
=>
a good default choice

XXH3 (aka xxhash-128) is even better BUT runs poorly on older 32 bit CPU => then XXH64 instead of XXH128

**Comment by fcorbelli** [comment]
Here you can find other infos
https://github.com/fcorbelli/zpaqfranz/wiki/Voodoo-checksums

LSS
If are paranoid, you can use BLAKE3 (very good, fast indeed)
If you have a newer CPU (with HW support) you can choose SHA256 (very fast, very widespreaded, ~2GB/s)
Or you can use the default, fast & good enough
