### ISSUE TITLE
encryption: add ChaCha20

### ISSUE THREAD

**Issue by Sanesecurity** [fcorbelli/zpaqfranz#127]
Probably a huge job to imperilment but maybe useful information for the future...

https://github.com/mrdcvlsc/ChaCha20-Poly1305

"Bottom line. Both AES-256 and XChaCha20 are great at encrypting and, therefore, securing sensitive data. But XChaCha20 really shines when it comes to simplicity and speed, making it a better choice for situations where you need both top performance and easy setup"

**Comment by fcorbelli** [comment]
Unfortunately, it's not possible, as it would break binary backward compatibility with zpaq archives, which is one of the fundamental goals of zpaqfranz (any archive created with zpaqfranz can be extracted with zpaq). For the client-server version, zcloud, which I haven't worked on for over a year, I use Twofish as an additional encryption layer (in this case, during data transmission). It's an algorithm that's somewhat inconvenient to use, but overall adaptable to "large batch" usage. ChaCha20 seems good, but I believe it has been studied less than Twofish. Therefore, almost certainly, but not guaranteed, I'll stick with the latter in zcloud (assuming I ever feel like finishing it).
[Here an interesting paper](https://kjar.spu.edu.iq/index.php/kjar/article/view/911)

**Comment by Sanesecurity** [comment]
Thanks for the update. AES256 should be fine anyway
