### ISSUE TITLE
"update -force" hangs

### ISSUE THREAD

**Issue by mirogeorg** [fcorbelli/zpaqfranz#131]
![image](https://github.com/user-attachments/assets/129efe28-959e-486b-9f5c-4f75b9d62250)

Franco, I tried to upgrade—it's my first time doing it—but it didn't work. Do you have any idea why this might be happening?

**Comment by fcorbelli** [comment]
This seems a bug due to multiple temp folder

**Comment by fcorbelli** [comment]
Yes, this really seems a bug in 60_6
You can update from <60.6 to 60.7
[Or download directly from here](https://www.francocorbelli.it/zpaqfranz/win64/)

**Comment by mirogeorg** [comment]
I'm using zpaqfranzhw.  It's not urgent to update right now.

**Comment by fcorbelli** [comment]
You can download here
https://www.francocorbelli.it/zpaqfranz/win64hw/

**Comment by mirogeorg** [comment]
thank you
