### ISSUE TITLE
list with sizes (new feature/ option in l command)

### ISSUE THREAD

**Issue by NSP-0123456** [fcorbelli/zpaqfranz#132]
I would like to have a list output with sizes instead of percentile or an option to remove extra header from pakka cmd and add attributes.

I currently use the terse option with l cmd, i just miss the sizes from this list.

I want to make a multiarc definition for zpaqfranz under total commander unfortunate the output is not as it was with zpaq 715.

**Comment by fcorbelli** [comment]
The concept of compressed file size does not exist in zpaq. The percentage you see displayed is a (rather rough) ESTIMATE of the space used. As paradoxical as it may seem, this information simply doesn't exist. Determining it accurately would require a huge slowdown (and I mean really significant). So, I can output the size, but it will be "fake," not correct.


If there is "something" that works for zpaq, it will also work for zpaqfranz. Binary backward compatibility is maintained; I worked hard to ensure that. Any kind of plug-in you use for zpaq will continue to work. There are some improvements (hash, CRC-32, and especially backups, plus ASCII-backed versions), but overall they are fairly marginal.

If you want 100% identical output between zpaq and zpaqfranz, maybe with the -715 switch, I can do it. I don't know what it would be useful for, but it's not difficult.

**Comment by fcorbelli** [comment]
[60_7q.zip](https://github.com/user-attachments/files/17266648/60_7q.zip)
In this pre-relase using the -715 switch (in the l list command) you should get an almost identical output of zpaq 7.15

**Comment by NSP-0123456** [comment]
This is almost perfect, i can view last file inside archive extract with verify some files !
I just miss the -terse option not effective.
just a guess, is it possible to have a list parameter in sfx ?

Grazie mille ;)

**Comment by fcorbelli** [comment]
> just a guess, is it possible to have a list parameter in sfx ?

Can you please explain?

**Comment by NSP-0123456** [comment]
I have a zpaq sfx like pippo.exe, (without the zpaq file) i can extract using x command but i cannot list to verify what is inside.  
if i use pakka, the file is not known as zpaq container, and zpaqfranz ask for a password (probably not knowing about the format also). 
zpaqfranz l nonZPAQfile.zzz,  ask for password for all non zpaq file.

zpaqfranz sfx pippo.exe do not recreate the pippo.zpaq.

**Comment by fcorbelli** [comment]
Mmmhhh... I can make a listsfx to (in zpaqfranz) to see what's inside the .exe
And sfxtozpaq to convert a .exe to a .zpaq

Does it make sense?

**Comment by NSP-0123456** [comment]
Yes !
I use more an more zpaq but sometime to distribute some archive the sfx is almost perfect as it is reduced and is enough for user not familiar to it. I do not which to distribute zpaqfranz due to the disk options to use with care. the sfx.exe is my zunpaq pgm ;)

**Comment by fcorbelli** [comment]
> due to the disk options to use with care 

???

**Comment by NSP-0123456** [comment]
I mean the k, f, rd command or the -kill option... Zpaqfranz is used by power user the one who can handle making archives with versions and not consider it as a simple ZIP File.

**Comment by fcorbelli** [comment]
Please update (zpaqfranz upgrade -force) to latest 60.7t
This pre-release include a .zpaq extractor

```
zpaqfranz sfx z:\1.exe -to z:\1.zpaq
```

**Comment by NSP-0123456** [comment]
Thx, it works great with full/relative path but a small issue is raised when only name is provided.
`zpaqfranz sfx 1.exe -to .\1.zpaq` is OK

`zpaqfranz sfx 1.exe -to 1.zpaq`

```
zpaqfranz v60.7t-JIT-LBLAKE3,SFX64 v55.1,(2024-10-08)
franz:-to                   <<1.zpaq>>
Extracting .zpaq <<1.zpaq>> from .exe <<1.exe>>

cannot write into <<1.zpaq>> -space to bypass
0.062s (00:00:00,heap 0|array 168|dt 0=>168)
```

**Comment by fcorbelli** [comment]
Too late.. to the next... 60.7u is released 😄

**Comment by fcorbelli** [comment]
![estrai](https://github.com/user-attachments/assets/07d86074-9fcf-48f9-b8cc-7d4124685d59)

**Comment by NSP-0123456** [comment]
Yes using wiki command with hw for sha1/2 and blake3 and adding -lurlmon. I will check with another GCC version.De : Franco Corbelli ***@***.***>Envoyé : mardi, octobre 8, 2024 5:05:19 PMÀ : fcorbelli/zpaqfranz ***@***.***>Cc : NSP-0123456 ***@***.***>; Author ***@***.***>Objet : Re: [fcorbelli/zpaqfranz] list with sizes (new feature/ option in l command) (Issue #132)
Did you compile yourself?
zpaqfranz v60.7u-JIT-LBLAKE3,SFX64 v55.1,(2024-10-08)

**Comment by fcorbelli** [comment]
Don't think it is a compiler issue
anyway...
```
g++ -O3 -DGUI -DHWSHA2 -DHWBLAKE3 blake3_windows_gnu.s zpaqfranz.cpp -o zpaqfranz -pthread -static -lurlmon 

or
g++ -O3 -s -DGUI -DHWSHA2 -DHWBLAKE3 blake3_windows_gnu.S c:/zpaqfranz/zpaqfranz.cpp -o c:/zpaqfranz/zpaqfranz.exe -pthread -static -Wall -Wpedantic -lurlmon 

```
depending on your compiler's configuration

**Comment by NSP-0123456** [comment]
I did the test with your compiled version or the one i compiled with gcc 13.2 ([nuwen.net/mingw.html) or 14.2 from w64devkit or mingw64. 
All the same result.

If i run with admin user or in elevate shell i got the same as prova.jpg but when using regular user having write access on the current folder I still have the issue.
just adding ./ or .\ in front of the name it solves the issue.
