### ISSUE TITLE
CC0-1.0 license

### ISSUE THREAD

**Issue by ppisar** [fcorbelli/zpaqfranz#133]
I was trying to add this program to Fedora distribution <https://bugzilla.redhat.com/show_bug.cgi?id=2238725>. Recently, there was a new momentum in it. When I checked for the latest version, 60.6, I discovered there is a code from <https://github.com/codewithnick/ascii-art> under CC0-1.0 license. Unfortunately this license is not allowed in Fedora for a code <https://docs.fedoraproject.org/en-US/legal/all-allowed/>.

I opened this issue only for you to know there is a such problem. Though I do not expect you to deal with it. Feel free to reject this issue. Nevertheless, If you were able to to replace the code with a differently licensed implementation, I could restart my work on packaging zpaqfranc for Fedora.

**Comment by fcorbelli** [comment]
![allowed](https://github.com/user-attachments/assets/76d84243-89b3-4a07-b36b-b627c5f95dc4)

Are you sure?

**Comment by fcorbelli** [comment]
I asked to the authors
Plan B: I rewrite everythin from scratch by myself

**Comment by fcorbelli** [comment]
Rewriting in progress...

**Comment by 197788** [comment]
> Rewriting in progress...

There also may be a similar project in github with a more flexible license...

**Comment by ppisar** [comment]
> Are you sure?

That listing is misleading. It does not have an explicit column for "allowed for a code". There is a different representation of the licenses that makes the distinction <https://docs.fedoraproject.org/en-US/legal/allowed-licenses/>. "allowed-content" <https://docs.fedoraproject.org/en-US/legal/license-approval/#_licenses_allowed_for_content> covers e.g. images. It does not cover code.

**Comment by fcorbelli** [comment]
No problem.
Now it is MIT-licensed, thanks to the author very kind
I will release the latest 60.7 just today (now implementing an user request, stripping SFX module)

**Comment by fcorbelli** [comment]
Please check the CURRENT zpaqfranz.cpp
(60.7t)
This one
https://github.com/fcorbelli/zpaqfranz/blob/main/zpaqfranz.cpp
This should meet Fedora's requirement

(Maybe I'll post some minor fixes, but nothing "big" is planned. Roll out of new "final" build in a while)

Thank you!

**Comment by ppisar** [comment]
Amazing. Thanks.
