### ISSUE TITLE
Windows Defender virus

### ISSUE THREAD

**Issue by KamikazeePL** [fcorbelli/zpaqfranz#134]
https://github.com/fcorbelli/zpaqfranz/releases/download/60.7/zpaqfranz.exe

Windows Defender virus warning on this file 
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FBearfoos.A!ml&threatid=2147731250

**Comment by fcorbelli** [comment]
Thank you.  
But I really does not care of "anti-something"
https://www.virustotal.com/gui/file/41d6256e8e944beb2780ef163282e909e73965efd96f210674546f3cb7e4d0dc

Less then everything, Microsoft's stuff


![jotty](https://github.com/user-attachments/assets/36c75eb8-a682-45a1-87fa-7c53a58e8412)
