### ISSUE TITLE
.zpaq, set .ZPAQ date to 01.01.1980 as a marker

### ISSUE THREAD

**Issue by mirogeorg** [fcorbelli/zpaqfranz#138]
Franco, RoboCopy create files with the date January 1, 1980, while copying. Once the copying is completed, it assigns the correct date. Do you think it’s a good idea for ZPAQFRANZ to do the same? This way, it would be clear which parts are likely unfinished.

**Comment by fcorbelli** [comment]
This will slow down A LOT extracting a large amount of files, especially over a network, where latency is so high

**Comment by mirogeorg** [comment]
Hello Franco. I had something else in mind; I didn't explain it well. When archiving, the .ZPAQ archive itself should have such a date until the archive is finalized.

**Comment by mirogeorg** [comment]
In my opinion, the idea to add -outputlog output.log is a good one.

For example, you may want to see everything that ZPAQFRANZ displays on the screen while logging it at the same time. By using >, you lose the real-time output on the screen. So having a log is a great feature. I would use both options -errorlog and outputlog.

**Comment by fcorbelli** [comment]
It required quite a bit of editing, so I hope I didn't “break” anything. It is included in the 60.8k version just uploaded

**Comment by mirogeorg** [comment]
Tested, it works ;)
