### ISSUE TITLE
Consider a .tmp extension for incomplete parts instead of .zpaq. This can improve compatibility with file sync applications.

### ISSUE THREAD

**Issue by mirogeorg** [fcorbelli/zpaqfranz#143]
Franco, I’m syncing .ZPAQ archives to a remote server using Syncthing. While new archive parts (archive0002.zpaq, etc.) are being created, Syncthing attempts to read them to generate hashes. It detects that they are currently being modified and starts over, leading to a repeated cycle.

Is there an option for ZPAQFRANZ to create files with a .tmp extension initially, and then only change the extension to .zpaq once the part is fully completed?

Syncthing doesn’t support exclusions based on date, and the developers refuse to work on such a feature.

**Comment by fcorbelli** [comment]
[60_9q.zip](https://github.com/user-attachments/files/17610014/60_9q.zip)

You can try backup with -tmp
(not very tested)

**Comment by mirogeorg** [comment]
please compile that version so I can test

**Comment by fcorbelli** [comment]
zpaqfranz upgrade -force

**Comment by mirogeorg** [comment]
looks good for now...

**Comment by mirogeorg** [comment]
With this patch, it is now safe to add to archives and run tests simultaneously.

**Comment by fcorbelli** [comment]
only if the are multipart

**Comment by sheckandar** [comment]
Not sure if I should file as a new issue.

`-tmp` doesn't work when using index files.

To reproduce:

```
./zpaqfranz a "/volume1/Netbackup/test-??????" "/volume1/homes" -nosynology -tmp -filelist -ssd
```

That creates a file test-000001.tmp and then renames it to test-000001.zpaq at the end.

Then I extract the index file:

```
./zpaqfranz x "/volume1/Netbackup/test-??????" -index "/volume1/Netbackup/test.index"
```

And then I run the backup again, but this time using the index file. The .tmp file is no longer created:

```
./zpaqfranz a "/volume1/Netbackup/test-??????" "/volume1/homes" -index "/volume1/Netbackup/test.index" -nosynology -tmp -filelist -ssd
```

**Comment by fcorbelli** [comment]
The index file do nothing in extraction
It is meant to MOVE the .zpaqs on a different storage space 

What and why you are doing?

**Comment by sheckandar** [comment]
I'm doing that because the backup files are stored in the cloud (BackBlaze) and downloading the data again costs lots of money (5 TB of data downloads every time doesn't make sense). So I use the index files.

I would like to avoid using rclone as it introduces another point of potential failure. So the index files are a perfect solution to that problem.

**Comment by fcorbelli** [comment]
By default, now, the backup command use .tmp
