### ISSUE TITLE
.ZPAQ date modified in future

### ISSUE THREAD

**Issue by mirogeorg** [fcorbelli/zpaqfranz#144]
My command line is:
zpaqfranz a VM_????.zpaq d:\vm -to "" -checktxt -tmp -not *swap*.* *.mrt *.rct  -m2 -t4

The result is that the .TXT file is created with the correct timestamp, but the ZPAQ archive is offset by +2 hours. I am in GMT+2 (winter time, which is currently exactly GMT+2).

![image](https://github.com/user-attachments/assets/0fcd7c0f-f885-47e1-adca-08ec7dc90851)

**Comment by fcorbelli** [comment]
You can try an update

**Comment by mirogeorg** [comment]
looks good now
