### ISSUE TITLE
-longpath switch not working with -destination switch

### ISSUE THREAD

**Issue by byplt** [fcorbelli/zpaqfranz#145]
When using -destination switch, longpaths are not detected. For example;

Working;
`zpaqfranz.exe a test.zpaq -input "C:\input.txt" -longpath`
![image](https://github.com/user-attachments/assets/2190f7bb-891e-418b-8891-53f8b1da73c1)

Not working;
`zpaqfranz.exe a test.zpaq -input "C:\input.txt" -destination "c:\dest.txt" -longpath`
![image](https://github.com/user-attachments/assets/5f24cdca-e92c-48b3-9678-7c4a1e53bacb)

**Comment by fcorbelli** [comment]
-longpath does not work with -to

**Comment by byplt** [comment]
I guess found a workaround, putting on prefix "\\?\" all of path in the input.txt, it worked, like -"longpath" switch (with "-destination" switch)
