### ISSUE TITLE
Windows: error shown with symlinked files 

### ISSUE THREAD

**Issue by houbit** [fcorbelli/zpaqfranz#15]
At first I have to thank you for [maintaining] this excellent tool!

Here a little issue using zpaqfranz v54.12, 
packing symlinked files under NTFS I get 

   "38385: WARN expected 0 getted <n> for <filepath>".

Further on this results in
   "38721: HOUSTON something seems wrong: expected  <m>, done <m> + <n>"
   "..."
   "... almost certainly incomplete"
   (that is definetly wrong, the archive is fine)

Kind regards

**Comment by fcorbelli** [comment]
Thank you for your recommendation.
Could you please do an actual example, even just for a single symlinked file?

```
"38385: WARN expected 0 getted for ".
```
should be a little difference
```
38385: WARN expected 0 getted 34 for thepippo.txt
```
It is indeed important to understand in which portion of the program (I think I understand it, but not for sure) the difference is generated

Can I prepare, in case, a specific debug version, so that you can test it, by putting it here (Windows 64 bit)?

**Comment by houbit** [comment]
Sorry my text was incomplete, used angle brackets without thinkin:

NTFS with symbolic link on a FILE:

"38385: WARN expected 0 getted for N".

Further on this results in
"38721: HOUSTON something seems wrong: expected M, done M+N"
"..."
"... almost certainly incomplete"
(that is definetly wrong, the archive is fine)`

Seems like the symlinked file was read (N bytes) but counted as 0 bytes.

Full example, zpaqfranz unpacked, symlink notes.txt.symlnk -> notes.txt:
'dir' =>
 Verzeichnis von A:\_zbackup\zpaq_test                                                                                                                                                                                                          27.04.2022  14:51    <DIR>          .                                                                                   
27.04.2022  14:51    <DIR>          ..                                                                                  
20.03.2022  18:41           293.202 blake3_windows_gnu.S                                                                
20.03.2022  18:41               5.677 CHANGELOG.md                                                                        
20.03.2022  18:41             15.391 differences715.txt                                                                  
20.03.2022  18:41                  470 Makefile                                                                            
20.03.2022  18:41             43.609 notes.txt                                                                           
27.04.2022  14:51    <SYMLINK>      notes.txt.symlnk [A:\_zbackup\zpaq_test\notes.txt]                                  
20.03.2022  18:41            27.754 README.md                                                                           
27.04.2022  14:51         1.065.373 x.zpaq                                                                              
20.03.2022  18:41           209.486 zpaq206.pdf                                                                         
20.03.2022  18:41         1.841.725 zpaqfranz.cpp                                                                                     
                      10 Datei(en),      3.502.687 Bytes                                                                                       
                        2 Verzeichnis(se), xxxxxxxx Bytes frei                                                              

"zpaq a test *"  (sorry, renamed it to zpaq for my own convinience only) =>
A:\_zbackup\zpaq_test>zpaq a test *                                                                                     
zpaqfranz v54.12-experimental (HW BLAKE3), SFX64 v52.15, compiled Mar 20 2022                                           
Integrity check type: XXHASH64+CRC-32 + CRC-32 by fragments                                                             
Creating test.zpaq at offset 0 + 0                                                                                      
Adding 2.437.314 (2.32 MB) in 9 files  at 2022-04-27 15:07:40                                                           
38385: WARN expected                   0 getted              43.609 for notes.txt.symlnk                                                                                                                                                        9 +added, 0 -removed.                                                                                                                                                                                                                           0 + (2.437.314 -> 2.437.314 -> 1.065.373) = 1.065.373                                                                                                                                                                                           38271: HOUSTON something seems wrong: expected 2.437.314, done 2.480.923                                                
38271: Corrupted source files? Lost connection? Cannot access? Media full?                                              
38271: =>The updated .zpaq archive is almost certainly incompleted                                                                                                                                                                              0.234 seconds (00:00:00)  (with errors)

**Comment by fcorbelli** [comment]
> Sorry my text was incomplete, used angle brackets without thinkin:
> 
> NTFS with symbolic link on a FILE:  

OK, this make sense (I never use symlink to file, only to folders :-)

> "38385: WARN expected 0 getted for N".
> 
> Further on this results in "38721: HOUSTON something seems wrong: expected M, done M+N" "..." "... almost certainly incomplete" (that is definetly wrong, the archive is fine)`
> 
> Seems like the symlinked file was read (N bytes) but counted as 0 bytes.

Exactly. The file size is taken the first time from the filesystem (and in this function, scandir (), will need to be corrected) and a second time after the block reading (to calculate the hash). In a normal situation the two data coincide. The foo.txt file was 1000 bytes BEFORE and will be 1000 AFTER

However, this does not always happen, as "someone" may change a file while the compression is in progress (can takes time, ever hours to complete)
So the file pippo.txt FIRST could be 1000 bytes large (... someone changes it ...) and THEN become let's say 1001. In this case the warning is shown

As mentioned, I would need, please, a run with -debug to understand if my interpretation is correct.
Thanks

**Comment by houbit** [comment]
I am VERY sorry about the delay, was in really bad health troubles.

> ..\54_13j a test * | tee ..\54_13j.log
> ..\54_13j a test * -debug | tee ..\54_13j-debug.log

54_13j.log:
`zpaqfranz v54.13j-experimental (HW BLAKE3), SFX64 v52.15, compiled Apr 28 2022
Integrity check type: XXHASH64+CRC-32 + CRC-32 by fragments
Creating test.zpaq at offset 0 + 0
Adding 2.437.314 (2.32 MB) in 9 files  at 2022-06-13 11:47:12
38385: WARN expected                   0 getted              43.609 for notes.txt.symlnk

9 +added, 0 -removed.

38271: HOUSTON something seems wrong: expected 2.437.314, done 2.480.923
38271: Corrupted source files? Lost connection? Cannot access? Media full?
38271: =>The updated .zpaq archive is almost certainly incompleted
`
54_13j-debug.log
`zpaqfranz v54.13j-experimental (HW BLAKE3), SFX64 v52.15, compiled Apr 28 2022
franz:DEBUG very verbose (-debug) 
21026: check_if_password of test.zpaq
Integrity check type: XXHASH64+CRC-32 + CRC-32 by fragments
Creating test.zpaq at offset 0 + 0
00000010 MY new t .
DIRECTORY;

00000010 MY new t ..
DIRECTORY;

00000020 MY new t blake3_windows_gnu.S
ARCHIVE;

00000020 MY new t CHANGELOG.md
ARCHIVE;

00000020 MY new t differences715.txt
ARCHIVE;

00000020 MY new t Makefile
ARCHIVE;

00000020 MY new t notes.txt
ARCHIVE;

00000420 MY new t notes.txt.symlnk
ARCHIVE;REPARSE_POINT;

29300: maybe Windows-symlinked file, fake size 0 real size 0 *
00000020 MY new t README.md
ARCHIVE;

00000020 MY new t zpaq206.pdf
ARCHIVE;

00000020 MY new t zpaqfranz.cpp
ARCHIVE;

Default sort
Adding 2.437.314 (2.32 MB) in 9 files 20006: converting to localtime 2022-06-13 09:50:50
20028: localtime is 2022-06-13 11:50:50
 at 2022-06-13 11:50:50
Model2: XXHASH64 2CB19869E0642796 CHANGELOG.md
Mode2: XXHASH64: <<2CB19869E0642796>> CRC32 <<CF04785D>> CHANGELOG.md
Model2: XXHASH64 5046DFD533DC8DA5 Makefile
Mode2: XXHASH64: <<5046DFD533DC8DA5>> CRC32 <<B04FD9A3>> Makefile
Model2: XXHASH64 51D9BB16C4688B8C README.md
Mode2: XXHASH64: <<51D9BB16C4688B8C>> CRC32 <<ADEA74AB>> README.md
Model2: XXHASH64 AB2D326F6ADC598D blake3_windows_gnu.S
Mode2: XXHASH64: <<AB2D326F6ADC598D>> CRC32 <<15956CE2>> blake3_windows_gnu.S
Model2: XXHASH64 D27913528DDE6FA4 differences715.txt
Mode2: XXHASH64: <<D27913528DDE6FA4>> CRC32 <<1030B35B>> differences715.txt
Model2: XXHASH64 C498B2481EA2C766 notes.txt
Mode2: XXHASH64: <<C498B2481EA2C766>> CRC32 <<010AA2D6>> notes.txt
Model2: XXHASH64 C498B2481EA2C766 notes.txt.symlnk
38385: WARN expected                   0 getted              43.609 for notes.txt.symlnk
Mode2: XXHASH64: <<C498B2481EA2C766>> CRC32 <<010AA2D6>> notes.txt.symlnk
Model2: XXHASH64 EA4527C120B47032 zpaq206.pdf
Mode2: XXHASH64: <<EA4527C120B47032>> CRC32 <<26121D8D>> zpaq206.pdf
Model2: XXHASH64 8DCD3E429C38D817 zpaqfranz.cpp
Mode2: XXHASH64: <<8DCD3E429C38D817>> CRC32 <<4ACAE94D>> zpaqfranz.cpp

9 +added, 0 -removed.

38271: HOUSTON something seems wrong: expected 2.437.314, done 2.480.923
38271: Corrupted source files? Lost connection? Cannot access? Media full?
38271: =>The updated .zpaq archive is almost certainly incompleted
33026: call xcommand on errorcode==2
Entering xcommand()
i_command   ||
i_parameter |38271: HOUSTON something seems wrong expected vs done|
Exit because empty i_command
`

**Comment by fcorbelli** [comment]
I hope you health is OK

[code]
Model2: XXHASH64 C498B2481EA2C766 notes.txt.symlnk
38385: WARN expected 0 getted 43.609 for notes.txt.symlnk
(...)
38271: HOUSTON something seems wrong: expected 2.437.314, done 2.480.923
[/code]
How do you have created 

notes.txt.symlnk?
Thank you

[54_16e.zip](https://github.com/fcorbelli/zpaqfranz/files/8892583/54_16e.zip)

PS the latest pre-release is this one

**Comment by houbit** [comment]
Thank You, I am fine now.

Just made a batch to create and run a test case:
- create directories ./node ./node/sub ./bro, each with a sample.txt and symlinks from ./node to the three sample.txt files (just in case, there may be  differences when adding from other targets then the actual dir).
- run zpaqfranz with / without '-debug' on ./node
- zip the batch, the used executable and all the log and results to zpaqfranz_test.zip

! The symlinks are created by Windows own mklink.com.
! Sadly you need administrator privileges to use this and also for the batch.

here the results:
[zpaqfranz_test.zip](https://github.com/fcorbelli/zpaqfranz/files/8919694/zpaqfranz_test.zip)

Anycase I hope this helps.
Kind regards

**Comment by fcorbelli** [comment]
Please test the current 55.4 release  
Thank you
