### ISSUE TITLE
commandline parsing issue?

### ISSUE THREAD

**Issue by mirogeorg** [fcorbelli/zpaqfranz#152]
![image](https://github.com/user-attachments/assets/79dafbc7-544a-4c9b-98e6-1a5de041311d)

Need to enclose path with quotes because it can contain spaces..

**Comment by fcorbelli** [comment]
No, it is not a parsing issue
It is standard Windows
\" will become an extended sequence
You must use two \\

\\"

**Comment by mirogeorg** [comment]
Is there a way to back up this folder? It's a VSS copy and accessible via UNC.

![image](https://github.com/user-attachments/assets/787e5b89-2142-4a0a-b140-785ace0bc6c4)

**Comment by fcorbelli** [comment]
Why not?
Of course you can
```
zpaqfranz a z:\ceppaflex.zpaq "\\franzk\z\folder with space"
```

**Comment by mirogeorg** [comment]
Franco, I can't make any sense of this. I'll try to explain again so you can understand me.

When the path I want to add to the archive starts with \\ and has no quotation marks, it works. However, when I add quotation marks, it doesn't work.
Besides the first issue, I've noticed another one: all parameters after the path somehow get included in the name of the path. For example, if I run zpaqfranz a archive "\\server\path" -t8
zpaqfranz seems to interpret the path as "\\server\path -t8"

Check what I've marked in red and the first screenshot in the post.
![image](https://github.com/user-attachments/assets/b5f81138-9ff5-40be-bb2e-20d91b6c5d53)

**Comment by fcorbelli** [comment]
Ahem... no
It is the \" that become an escape sequence for Windows
If you have folders with spaces, 
SIMPLY
use " BUT do not add the \

"this is good"
"this is not good\"

**Comment by mirogeorg** [comment]
Now I finally understood the nature of the problem. The issue likely stems from escaping in C because there’s no such problem in the command prompt, and currently, zpaqfranz behaves in a non-standard way, which causes confusion.

Perhaps it could detect such sequences and clearly explain where the problem originates from.
see the test: 

![image](https://github.com/user-attachments/assets/519f2496-86c1-4fa6-8af0-343fd6fd8bf0)

https://ss64.com/nt/syntax-esc.html

**Comment by fcorbelli** [comment]
Actually no, it has nothing to do with the program. It's a function of cmd.exe, that is, the Windows shell, and it applies to everyone (every software, written in whatever language). 
zpaqfranz has an "automatic" function to handle this case when it's the last parameter (that is, there's a `\"` right at the end of the line) to try to mitigate, or rather heuristically correct, the user's error, not the program's. 
Which, incidentally, is why on Windows it's better if the last parameter doesn't contain `"`.

This 
```
zpaqfranz blablabla -to "c:\wherever\" -noeta
```
is better than this
```
zpaqfranz blablabla -noeta -to "c:\wherever\"
```

### You must use two \

**Comment by mirogeorg** [comment]
Ok, you are right. Robocopy does the same.
Thank you.
