### ISSUE TITLE
Color-coded markup on files and folders on output.

### ISSUE THREAD

**Issue by adamantida** [fcorbelli/zpaqfranz#153]
Hi! I would like to propose to make a color marking, if it is a file - green, if it is a folder - blue. The colors are taken as an example.
For better visual understanding add `-tree` to output as a tree of folders and files.

For example:
![{8A932270-74DA-49FF-B813-244E89903A8F}](https://github.com/user-attachments/assets/2ff3251a-d6af-43dc-8186-d2c31c3008be)

**Comment by fcorbelli** [comment]
I'll think about it
Sadly it is very, very complex to output colors on Windows (!!!!!!)

Yes, very, very, VEERY complex, due to ancient compatibility issues
The main problem is the background color

**Comment by mirogeorg** [comment]
bit ZPAQFRANZ can output colors. 
All OK is green and errors are in RED.

**Comment by fcorbelli** [comment]
Well, warnings are yellow too! 😺
