### ISSUE TITLE
SFX GUI (or more interactivity)

### ISSUE THREAD

**Issue by dertuxmalwieder** [fcorbelli/zpaqfranz#19]
I consider using zpaqfranz for the sfx archives of [my Vim builds](https://tuxproject.de/projects/vim) as it squeezes one or two MB out of the file size (I tried it with v54). Yet, the usability is limited as the .exe files don’t provide a way to (easily) set the target directory.

I know that low-level Windows I/O is a mess, but I’d like to suggest that the SFX module lets the user choose the target directory, either with a pop-up or with a terminal input.

**Comment by fcorbelli** [comment]
A GUI I'd say no (I have exactly two sfx module users, too much work)  
If instead you want "something" that ask for the path where to extract, I can do it.  
If you give me a reliable C/C ++ function to read a string from the console, starting with a default one
I'm too lazy to write it :)

**Comment by fcorbelli** [comment]
If it is enough...
```
string getline(string i_default) 
{
    size_t maxline 	= 255+1;
    char* line 		= (char*)malloc(maxline); // sfx module, keep it small
	char* p_line 	= line;
	int c;

    if (line==NULL)
		error("744: allocating memory");
	
	if (i_default!="")
		printf("%s",i_default.c_str());

    while((unsigned)(p_line-line)<maxline) 
	{
        c = fgetc(stdin);
		
        if(c==EOF)
            break;

        if((*p_line++ = c)=='\n')
            break;
    }
    *--p_line = '\0';
    return line;
}
```

**Comment by fcorbelli** [comment]
[55_1n.zip](https://github.com/fcorbelli/zpaqfranz/files/9077387/55_1n.zip)
If you do not select a -sfxto the SFX module will ask

```
zpaqfranz a z:\myarchive.zpaq *.cpp -sfx z:\pippero\autoextraction.exe
```
Do you like ?

**Comment by dertuxmalwieder** [comment]
Yup! :) Well, a start. Thank you!
