### ISSUE TITLE
Request: add some real-world usage examples to the README?

### ISSUE THREAD

**Issue by Tony2** [fcorbelli/zpaqfranz#3]
Hi,

I learnt about zpaq during my search for some zfs-related issue.  zpaq sounds very interesting. Can you please add some real-world examples where zpaq is superior to conventional methods (like Apple TimeMachine, git, zfs snapshots etc.)?

**Comment by fcorbelli** [comment]
Your suggestion is very interesting, I will add some pages in the wiki

https://github.com/fcorbelli/zpaqfranz/wiki/Real-world:-compare-against-zfs-snapshot

https://github.com/fcorbelli/zpaqfranz/wiki/Real-world:-compare-against-7z-tar-rar-zstd-(conventional-archivers)

**Comment by Tony2** [comment]
Hi, 

[sorry for the late reply, I didn't get the chance to read the wiki thoroughly earlier]

I find the comparison against zfs-snapshot great, very informative. Especially the recommendation at the end, when to use zfs-snapshot and when zpaq: this kind of advice is really hard to get; the most common way is through hard-learned lessons.

If you could add some examples how you (or your users) use zpaq, it'd be much appreciated. For new users like me sometime understanding the concepts of a tool is not enough; seeing how other use it efficiently is often an eye-opening experience.
