### ISSUE TITLE
safer handling of passwords

### ISSUE THREAD

**Issue by brainchild0** [fcorbelli/zpaqfranz#36]
Would you consider adding features for safer handling of passwords?

At the moment, it appears that  the only supported method for the user providing a password is  to pass it directly on   command line.

This approach is insecure, for a variety of reasons, including the following:

- The text of the password is printed on the console.
- The text of the password is visible to any user on the system, by listing the process table. 
- The text of the password is recorded in the command history   maintained by the user's shell.

Common, safer ways for an application to allow passwords to be passed are as follows:

- Reading character input from an interactive prompt that  suppresses  echoing of the input text.
- Reading a file specified by the user.
- Invoking a command specified by the user   that  outputs the password, for capture by the application.

**Comment by fcorbelli** [comment]
Thanks for your suggestion.
Zpaqfranz already does

If you use a -key switch (without anything) the password is asked from console
If you work on already done archive (listing, adding etc) without -key at all, the password will be asked from console

**Comment by brainchild0** [comment]
Thanks for the explanation.

Have I missed the same explanation in the documentation, or has it not been included yet? I looked in the *Voodoo* section for encryption. I only noticed the support for the password included on the command line, which I believe is the same as the parent project.

**Comment by fcorbelli** [comment]
You can see updated infos in the embedded help.
And in the embedded examples (command he)

**Comment by fcorbelli** [comment]
I think I can close, thank you
