### ISSUE TITLE
Broken help

### ISSUE THREAD

**Issue by ratay** [fcorbelli/zpaqfranz#38]
Hi,
I found that somewhere around version 55.10 full help (h h) stopped working
and seems -diff is also not available for a longer time

is it possible to consider support for some helpful functions on linux in the future ?
 - preserving some file metadata like in tar ?
    (file owner, timestamp, symlink, ...)

thanks
Ratay

**Comment by fcorbelli** [comment]
Help is reworked to become more similar to debian package (short version)  
For symlink etc yes,I can. But a lot of work is needed.

**Comment by fcorbelli** [comment]
Update  
I am looking for tar-like metadata

**Comment by ratay** [comment]
good to know
with metadata and symlink support it would be really great full-featured backup tool
(but without it something important will always be missing)
thanks for the great work

**Comment by fcorbelli** [comment]
If you have any suggestions (even on help) please write.
Currently in development there is Windows dd-images (even of C:)

**Comment by ratay** [comment]
My programming skills on linux are read-only :((
So from what I read:
You read file attributes via stat(...)
In addition to the currently processed one, there are also other important ones: st_uid, st_gid, S_ISLNK, ... (https://linux.die.net/man/2/stat)
You write the attributes via chmod(...)
Similarly you can use chown(...) (https://linux.die.net/man/3/chown)
As for the symbolic links:
   read: https://man7.org/linux/man-pages/man2/readlink.2.html
   creation: https://man7.org/linux/man-pages/man2/symlink.2.html

Full help:
If you drop seppuku() from void Jidac::usage() it might work

**Comment by fcorbelli** [comment]
stat relies on a BIG structure (actually, two) with a LOT of data inside
Storing something that big requires (to maintain backward compatibility) a lot of work
Doable, in fact, but big (much bigger than -windate)  

Restoring is hard too (a lot of strange things)
Remember: zpaqfranz does not work "only" on Linux, but on Mac, BSD and Solaris and vSphere and NASes too. This file-system specific functions are a pain in the ass

Full help: without seppuku() you can get a LOT of help when inserting wrong parameters (even two or 3 times)
I'll restore (much easier)

**Comment by fcorbelli** [comment]
Please check this one (and do not forget a review on sourceforge, please :)
[56_2d.zip](https://github.com/fcorbelli/zpaqfranz/files/10103421/56_2d.zip)

**Comment by ratay** [comment]
I understand
It is annoying that the original author outlined the work with attributes, but did not leave space in the structures for their future completion.
Owner and group are really basic attributes without which a full backup of any unix-like system is not complete.
It's a pity.
But I believe that when you finish working on your current modifications, you will find some free time and space in "franz_block" to implement them. :)
Also, symlink support should not be so complicated - I don't think there is any need to change the structures.

The full help seems to work now (useful for example to compare changes between versions)
thanks

**Comment by fcorbelli** [comment]
It's a situation that I "feel" very little, and that's why I've never done it.
I work as a system administrator: all files are ... mine.
Mahoney has worked to achieve a very compact system, with very little wasted space
That's why the different structures between windows and linux
I am, on the other hand, much less interested in getting small files, also because I work with terabytes

**Comment by ratay** [comment]
I also work as a system administrator.
And all files belong to ... someone :))
And as always, I found a workaround:
`
getfacl -R -P * > aclbackup.txt
setfacl --restore=aclbackup.txt
find /root -type l -print0 | tar --null --files-from - -cvf linkbackup.tar
`

BTW
I tried the ESX version (ver. 5.5) and ended up like this:
`zpaqfranz v55.15q-experimental-ESX archiver,  (Sep 19 2022)
franz:DEBUG very verbose (-debug)
21026: check_if_password of zp.zpaq
zp.zpaq:
0 versions, 0 files, 0 fragments, 0 blocks, 0 bytes (0.00 B)
Default sort
Updating zp.zpaq at offset 0 + 0
Adding 551 (551.00 B) in 1 files (0 dirs), 1 threads
20006: converting to localtime 2022-11-29 09:42:20
@ 2022-11-29 09:42:20
Real write
39481: g_cdatasize  0
39482: g_htsize     0
39431 writeJidacheader -1
23013: zpaqfranz error: St9bad_alloc

0.047 seconds (00:00:00)  (with errors)
33026: call xcommand on errorcode==2
Entering xcommand()
i_command   ||
i_parameter |Out of memory|
Exit because empty i_command
`

**Comment by fcorbelli** [comment]
Esx runs on a Centos 32 bit of about 15 years ago (!) does not allocate happlily RAM to anything else than VM
On esx I use the r (robocopy/rsync) in  a ghetto script and sum to make hashes
A to store logs into a permanent datastore

I find 0 documentation (offical from vmware) for custom made exes
If you have any please le me know

**Comment by ratay** [comment]
I also use ghetto - I thought I would supplement it with zpaq.
Then why are you publishing the version for ESX when it doesn't work?

**Comment by fcorbelli** [comment]
Well it works for me, or better for my job

Everything from zpaq to zpaqfran are my very own 'pieces' of work
I need this, I implement
I do NOT need? I don't, unless someone else ask
I do not need a zpaq compression into esxi: little free CPU, slow non cached filesystem,therefore no developing

Instead I need a sector based windows imager and a ransom-resilient nix

PS on Esxi 6.5 it compress (small) files,at least on mine servers
