### ISSUE TITLE
Error with -vss switch

### ISSUE THREAD

**Issue by graphixillusion** [fcorbelli/zpaqfranz#41]
Hi there. I was trying using zpaqfranz to "backup" a folder with open files inside it from another running application. 
The command i used is:

`zpaqfranq a test.zpaq D:\LOCKEDFOLDER -vss`

but i'm getting this as result:

```
zpaqfranz v56.2g-JIT-L (HW BLAKE3), SFX64 v55.1, (01 Dec 2022)
franz: VSS Volume Shadow Copy (-vss)
02/12/2022 01:30:35 VSS: starting
02/12/2022 01:30:39 VSS: intermediate
42360: something wrong preparing

3.360 seconds (000:00:03) (with errors)
```
Any clue?

**Comment by fcorbelli** [comment]
-vss is not meant (anymore) to backup a folder, but the C drive, via commands g and q
```
zpaqfranz q z:\1.zpaq -frugal
```
I then no longer checked the copying of individual folders. I can check though
Just one detail: was zpaqfranz launched with admin rights?

**Comment by fcorbelli** [comment]
[56_3a.zip](https://github.com/fcorbelli/zpaqfranz/files/10140112/56_3a.zip)
Can you please check the pre-release build attached?

You can quickly check with
```
zpaqfranz a z:\nor.zpaq c:\windows\system32\config
zpaqfranz a z:\vss.zpaq c:\windows\system32\config -vss
```
of course a very bad SHARING VIOLATION expected on config folder

Let me know, and thank you

PS fuc*** != =! arrrgghhh!!! :)

**Comment by graphixillusion** [comment]
@fcorbelli first of all thanks to you for awesome code and support.

1. This is a try on the TelegramPortable folder while telegram is running:

```
zpaqfranz v56.3a-JIT-L (HW BLAKE3), SFX64 v55.1, (02 Dec 2022)
franz: VSS Volume Shadow Copy (-vss)
02/12/2022 16:36:07 VSS: starting
02/12/2022 16:36:12 VSS: end
Creating test.zpaq at offset 0 + 0
Adding 364.748.027 (347.85 MB) in 3.326 files (426 dirs), 2 threads @ 2022-12-02 16:36:07
3.752 +added, 0 -removed.

0 + (364.748.027 -> 364.757.312 -> 289.850.151) = 289.850.151 @ 5.87 MB/s
02/12/2022 16:37:06 VSS: starting release
02/12/2022 16:37:07 VSS: end releasing

38271: HOUSTON expected 364.748.027, done 364.757.312, diff 9.285
38271: This could be 'normal' for a VSS operation

59.984 seconds (000:00:59) (with errors)
```

2. This is running with your example:

```
D:\>zpaqfranz a vss.zpaq c:\windows\system32\config -vss
zpaqfranz v56.3a-JIT-L (HW BLAKE3), SFX64 v55.1, (02 Dec 2022)
franz: VSS Volume Shadow Copy (-vss)
02/12/2022 16:42:51 VSS: starting
02/12/2022 16:42:53 VSS: end
Creating vss.zpaq at offset 0 + 0
Adding 225.774.937 (215.32 MB) in 184 files (232 dirs), 2 threads @ 2022-12-02 16:42:51
416 +added, 0 -removed.

0 + (225.774.937 -> 177.040.358 -> 33.503.839) = 33.503.839 @ 17.78 MB/s
02/12/2022 16:43:03 VSS: starting release
02/12/2022 16:43:03 VSS: end releasing

38271: HOUSTON expected 225.774.937, done 225.824.377, diff 49.440
38271: This could be 'normal' for a VSS operation

12.687 seconds (000:00:12) (with errors)
```

**Comment by fcorbelli** [comment]
Sorry, I am not sure 100%, I do not use telegram (on PC), the -vss is for the (upcoming) "image sector by sector on VSS"  

You can try to
- backup with VSS when telegram is "running"
- stop the executable
- make another backup
- restore both (VSS and "normal"), then compare


If you want please leave a review on
https://sourceforge.net/projects/zpaqfranz/
and put a star on github (if you haven't already).
Any comment or suggestion is welcome
Thanks for collaboration

PS you will be, from the next release,
```
15 Thanks to https://github.com/graphixillusion for "lost" -vss
```

**Comment by graphixillusion** [comment]
@fcorbelli thanks to you for the great support. Already done the stars on here and review on sourceforge

**Comment by fcorbelli** [comment]
Ok!
