### ISSUE TITLE
longpath

### ISSUE THREAD

**Issue by ratay** [fcorbelli/zpaqfranz#42]
Hi Franco,
I'm not sure if I'm using the -longpath attribute on windows correctly
Well, it seems to me that when using it, only the first file / folder is added to the archive
e.g.:
d:\main\1file.txt
d:\main\2folder ...
d:\main\3folder ...
`zpaqfranz.exe a test.zpaq d:\main -longpath`
  - only d:\main\1file.txt was added to the archive
Without the -longpath attribute, the entire structure is added (1file.txt, 2folder ..., 3folder ...)

**Comment by fcorbelli** [comment]
I need some more infos, please
This is a z:\main folder, with
1file.txt inside
2folder, with 1 file inside
3folder, with 1 file inside

3 .txt files

```
dir z:\main /s
 (...)
 Directory di z:\main

03/12/2022  10:24                14 1file.txt
03/12/2022  10:24    <DIR>          2folder
03/12/2022  10:25    <DIR>          3folder

 Directory di z:\main\2folder
03/12/2022  10:24                 6 this_is_file_two.txt
               1 File              6 byte

 Directory di z:\main\3folder
03/12/2022  10:25                 7 this_is_file_three.txt
               1 File              7 byte

```

now
```
C:\zpaqfranz>zpaqfranz a z:\test z:\main -longpath
zpaqfranz v56.3a-JIT-L (HW BLAKE3), SFX64 v55.1, (02 Dec 2022)
franz:Long path (on Windows)
38992: INFO: getting Windows' long filenames
Creating z:/test.zpaq at offset 0 + 0
Adding 27 (27.00 B) in 3 files (2 dirs), 32 threads @ 2022-12-03 10:28:53
5 +added, 0 -removed.

0 + (27 -> 27 -> 1.377) = 1.377 @ 870.00 B/s

0.031 seconds (00:00:00) (all OK)
```

And now
```
C:\zpaqfranz>zpaqfranz l z:\test.zpaq
zpaqfranz v56.3a-JIT-L (HW BLAKE3), SFX64 v55.1, (02 Dec 2022)
z:/test.zpaq:
1 versions, 5 files, 3 fragments, 3 blocks, 1.377 bytes (1.34 KB)


- 2022-12-03 10:24:44                  14 A     z:/main/1file.txt
- 2022-12-03 10:24:58                   0 D     z:/main/2folder/
- 2022-12-03 10:24:59                   6 A     z:/main/2folder/this_is_file_two.txt
- 2022-12-03 10:25:10                   0 D     z:/main/3folder/
- 2022-12-03 10:25:12                   7 A     z:/main/3folder/this_is_file_three.txt

                   27 (27.00 B) of 27 (27.00 B) in 5 files shown
                1.377 compressed

0.015 seconds (00:00:00) (all OK)
```

Can you please "zip" your test folder and attach here, for debug?
(of course NO relevant information inside files, only a test)

Thank you

**Comment by ratay** [comment]
I did other tests
and I think I have come up with something:
```
C:\Scripts>zpaqfranzhw a std1 d:\main  -debug >std1.log
C:\Scripts>zpaqfranzhw a std2 d:\main\ -debug >std2.log
C:\Scripts>zpaqfranzhw a std3 d:\main\* -debug >std3.log
C:\Scripts>zpaqfranzhw a long1 d:\main -debug -longpath >long1.log
C:\Scripts>zpaqfranzhw a long2 d:\main\ -debug -longpath >long2.log
C:\Scripts>zpaqfranzhw a long3 d:\main\* -debug -longpath >long3.log
```
[tests.zip](https://github.com/fcorbelli/zpaqfranz/files/10146451/tests.zip)

**Comment by fcorbelli** [comment]
You are right
To discriminate folders from non-folders you should DO not use \ or \* on folders with -longpath

d:\main and not d:\main**SOMETHING**

**Comment by ratay** [comment]
And how to deal with root folder ?
Neither D:\ nor D: seem to work (and this was the situation where I came up with it)
it also seems to me that the -not option has a problem with -longpath:
```
C:\Scripts>zpaqfranzhw a std4 d:\main -debug -not d:\main\2folder >std4.log
C:\Scripts>zpaqfranzhw a long4 d:\main -debug -longpath -not d:\main\2folder >long4.log

```

**Comment by fcorbelli** [comment]
An update is needed.  
Working in progress...

**Comment by fcorbelli** [comment]
[56_3c.zip](https://github.com/fcorbelli/zpaqfranz/files/10147055/56_3c.zip)
Please test the attached pre-release

**Comment by fcorbelli** [comment]
[56_3d.zip](https://github.com/fcorbelli/zpaqfranz/files/10154231/56_3d.zip)
This should take care of UNC short and longpath too

```
\\franzk\z
\\franzk\z\*
\\franzk\z\*.*
\\franzk\z\thefolder
```
Please check and let me know if OK

**Comment by ratay** [comment]
I didn't find any defects
Everything looks fine

BTW
How is the work on the server edition going?
It looks very interesting

**Comment by fcorbelli** [comment]
>How is the work on the server edition going?
>It looks very interesting  

Planned, way complex.
Current focus on windows C: imaging
