### ISSUE TITLE
Windows - Parameters are added to folder name on x?

### ISSUE THREAD

**Issue by highend** [fcorbelli/zpaqfranz#45]
Using the current version v56.4 on Windows Server 2022 x64

This runs fine on the first run:
```
zpaqfranz.exe x "D:\!XYplorer\!Archive\17\40\v17.40.zpaq" "D:/!XYplorer/!Archive/17/40/XYplorerFree 17.40.0100" -to "D:\!XYplorer\!Fresh\XYplorerFree 17.40.0100\"
```

Now imagine I'd like to extract again and overwrite stuff:
In this case the -force parameter isn't used, it's just appended to the destination folder name?
`XYplorerFree 17.40.0100 -force` in `D:\!XYplorer\!Fresh`
```
zpaqfranz.exe x "D:\!XYplorer\!Archive\17\40\v17.40.zpaq" "D:/!XYplorer/!Archive/17/40/XYplorerFree 17.40.0100" -to "D:\!XYplorer\!Fresh\XYplorerFree 17.40.0100\" -force
```

Another issue? (or maybe I'm just doing it wrong...)
E.g. extract only a specific version (the archive has 29 versions):
It extracts the whole archive into `XYplorerFree 17.40.0100 -until 29`  not only the 29th version...
```
zpaqfranz.exe x "D:\!XYplorer\!Archive\17\40\v17.40.zpaq" -to "D:\!XYplorer\!Fresh\XYplorerFree 17.40.0100\" -until 29
```

**Comment by fcorbelli** [comment]
I am refactoring in the handling of internal flags (in build 57), 
it is therefore difficult to give an answer. 

Can you please attach a debug archive to this post?

You can  make by
```
zpaqfranz a z:\thedebug.zpaq "d:\!XYplorer" -debug -zero
```
_-debug -zero means retaing everything (file names and size), but filled with 0_

Then add the .zpaq into a zip (yep, github wants zip)
Thank you

**Comment by highend** [comment]
Don't know if this will help you much (this archive only has a single version) but nonetheless, I've created it (and redirected the output of it into a file).
Put the `debug.zpaq` and `debug_log.txt` into a .zip and attached it...
[debug.zip](https://github.com/fcorbelli/zpaqfranz/files/10472047/debug.zip)

**Comment by fcorbelli** [comment]
This is the (infamous) " on Windows
```
zpaqfranz.exe x "D:\!XYplorer\!Archive\17\40\v17.40.zpaq" "D:/!XYplorer/!Archive/17/40/XYplorerFree 17.40.0100" -to D:\!XYplorer\!Fresh\XYplorerFree_WITHOUTSPACE -force
```

I will seek for a solution :) (now I am porting on... Haiku!!)

**Comment by highend** [comment]
Mh. I hope you find one :)

Should this work (extract only that (existing) version)?
It always extract the whole archive, not a single version out of it...
```
zpaqfranz.exe x "D:\!XYplorer\!Archive\17\40\v17.40.zpaq" -to D:\!XYplorer\!Fresh\XYplorerFree_WITHOUTSPACE -until 29
```

**Comment by fcorbelli** [comment]
It is a Windows "thing", require some kind of... kludge

Short version: without " (=> no space inside folder name) should works fine  
Avoid as much as possible the spaces (!)

On *nix it is the opposite (use " everywhere, and you will be fine)

**Comment by highend** [comment]
As I said, even when I don't use spaces (and no double quotes around the extraction path), it extracts the full archive, not the specific version...

**Comment by fcorbelli** [comment]
-until something -to whereyouwant

**Comment by fcorbelli** [comment]
If you can please attach a "real" multiversion test file  
thank you

**Comment by highend** [comment]
Sorry, I think I got it now... It's extracting everything from the beginning of the archive up to that version with -until K :)
For whatever reason I was thinking it would extract only the version K, not everything before.
My bad, sorry.

**Comment by fcorbelli** [comment]
If you ONLY want the files added in version K, yes... you can... :)
with -range and -all
```
zpaqfranz x incrementale.zpaq -to z:\extracted -all -range 300:300
```
On your's version this will  make a lot of empty dirs, but with the **z:\extracted\0300** filled

**Comment by highend** [comment]
It's even a bit easier for this archive:
```
zpaqfranz.exe x archive.zpaq "D:/XYplorerFree 17.40.0100" -to D:\_extracted_\XYplorerFree_17.40.0100
```
As long as that path (forward slashes are required even under Windows) does only exist once (and for this special archive type that's the case), I can extract it with the command above. No `-until` or `-range` required.

**Comment by fcorbelli** [comment]
Can you please check the attached pre-release?
[57_2b.zip](https://github.com/fcorbelli/zpaqfranz/files/10520904/57_2b.zip)
Thank you

**Comment by highend** [comment]
Sorry, just got home...

Tried that version and didn't discover any problems with it (creating archives / extracting from archives wise)...

**Comment by fcorbelli** [comment]
OK for now I close
(PS new 57_2 is released)
