### ISSUE TITLE
How to exclude some files

### ISSUE THREAD

**Issue by nxshock** [fcorbelli/zpaqfranz#46]
Is there any way to exclude some files from archiving? For example, do not include temporary directories like `/tmp` or `/var/tmp` when archiving `/`.

**Comment by nxshock** [comment]
Looks like I found solution in ZPAQ docs: `-only` to include, `-not` to exclude files.

**Comment by fcorbelli** [comment]
Yes, you can :)  
Those are arrays (vectors) so you can use more than one -not or -only
