### ISSUE TITLE
Jolly in archivename and bad frag IDs

### ISSUE THREAD

**Issue by Erol-2022** [fcorbelli/zpaqfranz#47]
Hello Mr. Corbelli,

I managed to create a simple delta / patch system using Zpaqfranz but I encountered some problems.

The purpose is to create a delta file from the wim archives below captured with wimlib :

Source file, the base of the delta :

Hp-ProBook-850-G8-Win10-2022-H2-SysPrep.wim , size 10.881.277.996 bytes

This is the new file, the delta will be created from this one :

Hp-450-G7-Win10-2022-H2-Sysprep.wim, size 11.122.396.929 bytes

Processing the base file :

```
D:\Tools>zpaqfranz.exe a Archive?.zpaq Hp-ProBook-850-G8-Win10-2022-H2-SysPrep.wim -index archive-index.zpaq
zpaqfranz v57.3f-JIT-L (HW BLAKE3),SFX64 v55.1, (15 Feb 2023)
franz:-index                     archive-index.zpaq
Creating Archive1.zpaq at offset 0 + 0
Adding 10.881.277.996 (10.13 GB) in 1 files (0 dirs), 32 threads @ 2023-03-06 23:25:11
1 +added, 0 -removed.

0 + (10.881.277.996 -> 10.639.858.136 -> 10.616.381.783) = 10.616.381.783 @ 80.13 MB/s

129.750 seconds (000:02:09) (all OK)

```
The new Archive2.zpaq file smaller than the first version will be the delta \ patch file :

```
D:\Tools>zpaqfranz.exe a Archive?.zpaq Hp-450-G7-Win10-2022-H2-Sysprep.wim -index archive-index.zpaq
zpaqfranz v57.3f-JIT-L (HW BLAKE3),SFX64 v55.1, (15 Feb 2023)
franz:-index                     archive-index.zpaq
archive-index.zpaq:
1 versions, 1 files, 151.245 frags, 639 blks, 4.303.304 bytes (4.10 MB)
Creating Archive2.zpaq at offset 0 + 10.616.381.783
Adding 11.122.396.929 (10.36 GB) in 1 files (0 dirs), 32 threads @ 2023-03-06 23:28:10
1 +added, 0 -removed.

0 + (11.122.396.929 -> 3.594.298.431 -> 3.587.561.008) = 3.587.561.008 @ 88.28 MB/s

120.390 seconds (000:02:00) (all OK)
```

Archive1.zpaq, 10.616.381.783 bytes
Archive2.zpaq , 3.587.561.008 bytes

Archive2.zpaq is copied to the remote server.

Calculating the MD5 signature of the wim file to be regenerated on the remote server :

D:\Tools>md5sum.exe Hp-450-G7-Win10-2022-H2-Sysprep.wim
8d87b8003518e67c5ba0cc1f216aabd4 *Hp-450-G7-Win10-2022-H2-Sysprep.wim

On the command prompt of the remote system :

Creating the same preliminary archive from the base file, Hp-ProBook-850-G8-Win10-2022-H2-SysPrep.wim which is already transferred to this server :

```
F:\Tools>zpaqfranz.exe a Archive?.zpaq Hp-ProBook-850-G8-Win10-2022-H2-SysPrep.wim -index archive-index.zpaq
zpaqfranz v57.3f-JIT-L (HW BLAKE3),SFX64 v55.1, (15 Feb 2023)
franz:-index                       archive-index.zp
Creating Archive1.zpaq at offset 0 + 0
Adding 10.881.277.996 (10.13 GB) in 1 files (0 dirs), 2 threads @ 2023-03-07 09:55:19
1 +added, 0 -removed.

0 + (10.881.277.996 -> 10.639.858.136 -> 10.616.381.783) = 10.616.381.783 @ 70.65 MB/s

146.922 seconds (000:02:26) (all OK)
```

Extracting the new wim file, Hp-450-G7-Win10-2022-H2-Sysprep.wim :

```
F:\Tools>zpaqfranz.exe x Archive?.zpaq -only Hp-450-G7-Win10-2022-H2-Sysprep.wim
zpaqfranz v57.3f-JIT-L (HW BLAKE3),SFX64 v55.1, (15 Feb 2023)
43787: Jolly in archivename!
franz:-only                 Hp-450-G7-Win10-2022-H2-Sysprep.wim
--------------------------------------------------------------------------------------------------------------------
Searching for archive(s) in <<Archive?.zpaq>>
Founded 2 archive(s), extracting
Archive1.zpaq:
1 versions, 1 files, 151.245 frags, 639 blks, 10.616.381.783 bytes (9.89 GB)
Extracting 0 bytes (0.00 B) in 0 files (0 folders) with 2 threads

Archive2.zpaq:
1 versions, 1 files, 198.198 frags, 218 blks, 3.587.561.008 bytes (3.34 GB)
Hp-450-G7-Win10-2022-H2-Sysprep.wim: bad frag IDs, skipping...
Extracting / bytes (-1.00 B) in 1 files (0 folders) with 2 threads

0.328 seconds (00:00:00) (all OK)

```
Here, I receive two messages : Jolly in archivename! and bad frag IDs
What does mean Jolly in archivename?

I managed to extract Hp-450-G7-Win10-2022-H2-Sysprep.wim using Mr.Mahoney's zpaq tool :

```
F:\Tools>zpaq64 x Archive?.zpaq -only Hp-450-G7-Win10-2022-H2-Sysprep.wim
.
.
99.54% 0:00:00 [197505..197704] -> 16641940
99.69% 0:00:00 [197705..197924] -> 16755357
99.84% 0:00:00 [198187..198198] -> 1330347
99.85% 0:00:00 [197925..198186] -> 16726187
131.328 seconds (all OK)
```

The MD5 value of the file is correct and it's the same as the original one :

F:\Tools>md5sum.exe Hp-450-G7-Win10-2022-H2-Sysprep.wim
8d87b8003518e67c5ba0cc1f216aabd4 *Hp-450-G7-Win10-2022-H2-Sysprep.wim

I guess both of those issues should be reviewed as  Mr.Mahoney's zpaq does not complain about the .my zpaq archives.

Thanks,

Erol

**Comment by fcorbelli** [comment]
This should be at 99% a bug in a new function, the multiple extraction (jolly)

You can do something like this now

zpaqfranz x *allthe.zpaq

But it catch ? too, used for multipart archive (first guess)

Please check with build 55
If no error => it is a bug => do not worry, I will fix today

Thanks for the report

**Comment by fcorbelli** [comment]
Ps there is a specific function (switch) to hash check to remote files, and the -big to make it very easy to quickly check

**Comment by Erol-2022** [comment]
Hello,

zpaqfranz v55.16h does not display the two warning messages. Thanks.

**Comment by fcorbelli** [comment]
[57_4d.zip](https://github.com/fcorbelli/zpaqfranz/files/10909755/57_4d.zip)
Please test the attached pre-release

Turning back on remote backup I suggest rsync (if you can) with --append, and zpaqfranz with -checktxt, no multivolumes

Scenario:
- Local client, Windows
- Remote server, Linux (or FreeBSD or whatever), with rsync-on-keys

```
zpaqfranz a z:\thebackupfile.zpaq thefolders -longpath -checktxt -key pippo
```
Now put the .zpaq, and the .txt, to the remote server, start a verify (on the remote server) checking the hash, something like (just a snippet)

Please note, the first (.txt) without --append, the second (.zpaq) WITH --append

```
c:\franco\rsync -e "c:\franco\ssh -i /cygdrive/c/franco/backup_franco" -I --chmod=a=rwx,Da+x  z:\thebackupfile.txt  franco@the-remote-ip:/home/franco/copie/
c:\franco\rsync -e "c:\franco\ssh -i /cygdrive/c/franco/backup_franco" -I --chmod=a=rwx,Da+x  --append z:\thebackupfile.zpaq  franco@the-remote-ip:/home/franco/copie/

c:\franco\ssh -p 22 -i c:\franco\backup_franco franco@the-remote-ip "/home/franco/copie/checkfranco.sh" "thebackupfile.zpaq" "thebackupfile.txt" "where-to-get-log@myemail.it"```

on the remote script something like ...
```
/usr/local/bin/zpaqfranz dir "/home/franco/copie/" -noeta >/tmp/checkfranco.txt

/usr/local/bin/zpaqfranz sum /home/franco/copie/$1 -big -noeta -checktxt /home/franco/copie/$2 >>/tmp/checkfranco.txt

if [ -f /tmp/checkfranco.txt ]; then
    /usr/local/bin/smtp-cli --missing-modules-ok  -server=mail.mygoodemail.com --port 587 -4 -user=log@mygoodemail.com -pass=mygoodpassword -from=log@mygoodemail.com -to whereiwantthelog@gmail.com -cc $3 -subject  "CHECK-franco-remote-$1" -body-plain=/tmp/checkfranco.txt
fi
```
In this example the password (of the encrypted .zpaq) will not "travel" ever on the remote server
Of course if this is a really "your" server you can change the script with a t (test) with the -key in plaintext

**Comment by Erol-2022** [comment]
Hi Mr. Corbelli,

The new version supplied with the zip file 57_4d.zip is solving the problem,many thanks. I should be more specific and mention about the rdiff tool : 

https://linux.die.net/man/1/rdiff

rdiff is a very powerful tool creating patch files once you have a signature file.

Returning back to your questions : 

Why archive? This is a multipart archive (archive1.zpaq, archive2.zpaq... archive9.zpaq)
Why -index?

The first member of the multipart archive acts like the signature file calculated from the "old-file" :

`rdiff [options] signature old-file signature-file`

To create a multipart archive, you need to supply the -index option. Now, here is the crucial part : Since the "new file" is sharing a lot of common data with the "old file" , the "delta file" will be generally smaller, this one is the second member of the multiparts. It's easy to create the first element of the consecutive archive parts both on the local and remote server. Zpaqfranz excels at this point as it can run much more faster than a typical rdiff patch operation. 

`rdiff.exe delta Hp-ProBook-850-G8-Win10-2022-H2-SysPrep-Mart2023.wim.rdiffsign Hp-450-G7-Win10-2022-H2-Sysprep.wim Hp-450-G7-Win10-2022-H2-Sysprep.wim.rdiffdelta
`
The command above is running since one hour on the server and yet the operation is not complete. It took only two minutes to create the second zpaq archive named Archive2.

Thanks for your efforts on presenting the cooperation zpaqfranz and rsync.

Have a nice day,

Erol
