### ISSUE TITLE
zpaq gui numkey issue

### ISSUE THREAD

**Issue by graphixillusion** [fcorbelli/zpaqfranz#49]
Hi there. 
First of all i need to say that i simply love the new GUI, even if is still not complete! What a beautiful idea!
During my playing with that, i have found a little issue that i want to report.

Under the filter/search/replace/extract dialog, this two keys from the numpad doesn't work: **/** and *****
And this other two keys have a strange effects: **+** and **-**
Actually the + and - keys are binded to another function but what if i need to insert these symbols as part of a filename? Like "zpaq+.txt" or "zpaq-advanced.txt"

Thank you!

**Comment by fcorbelli** [comment]
As mentioned it is only a very first alpha version, more for the next step (PAKKA-like)
AKA: for every file a different sort
Example

file1.cpp
v001 2023-02-03 3.000 byes
v002 2023-02-05 3.500 bytes
v003 2023-02-06 4.000 bytes

pippo.cpp
v001 2023...
v002 ....

work in progress...
