### ISSUE TITLE
Default to an archive with same name as the target directory

### ISSUE THREAD

**Issue by todd-a-jacobs** [fcorbelli/zpaqfranz#55]
## Expected Behavior

I intuitively expect that when passed a directory named `foo` that zpaqfranz would create a `foo.zpaq` archive using the name of the directory as a default. For example:
    
    zpaqfranz a foo

## Actual Behavior

This is likely because it's not obvious what a default output archive should be named, but `zpaqfranz a foo` just prints the usage information. Instead, I have to specify both the directories and files after naming an archive, like so:

    zpaqfranz a foo.zpaq foo

This is in contrast to tools like lrztar which will do the "sensible thing" and simply create a sensibly-named archive *unless one already exists* in which case I need to specify the `-f` flag to force an overwrite, or the `-o` flag to specify the output file.

## Side Note

It would be nice if zpaqfranz played nicely with lrztar, which many other formats do (including zpaq, although zpipe doesn't currently work correctly on the M2 processor making lrztar with standard zpaq currently unusable).

**Comment by fcorbelli** [comment]
In case your command does not match the expected syntax, you will get the usage as output.
For example
```
zpaqfranz l public.zpaq -toz z:\pippo
```
I chose not to display the help for the individual command because, often, it is very long

```
zpaqfranz h a
```

I don't normally use lrztar, I'll take a closer look tomorrow

**Comment by fcorbelli** [comment]
Every single help is highly appreciated, and my documentation support is modest, to say the least

**Comment by todd-a-jacobs** [comment]
@fcorbelli Almost right. See comments and examples below for a (hopefully) clearer set of examples.

## With Current Command-Line Signature and No Output-File Flag
Assuming this only works when naming a single target file or directory (which it almost has to currently since the target `.zpaq` file needs to be named _before_ the files/directories to add to the archive) and if there's no flag to define an output file, then:

1. It's possible that `pippero` is a file or tarball, in which case it should do the same thing but without the recursion since it's a file and not a directory.
2. There should probably be an ENOENT error whether `pippero` is a file *or* a folder since you're trying to add something that isn't there.

## Deciding Whether to Delay Errors or Abort Immediately
### With an Output-File Flag
However, _if_ there were a flag for naming the zpaq archive and all non-arguments were just files or directories to compress, then you might want to think about whether it makes sense to error immediately before spending a lot of time compressing things if only _some_ of them are missing, or whether (like tar) you want to delay any ENOENT or other errors until after the rest of the archiving is done. For example, if we imagine a `-o foo` or `-o foo.zpaq` flag:

```bash
# Add pippero1 and pippero2 to foo.zpaq; if pippero1 is missing, report that later
# and compress pippero2 anyway. The user could then call `zpaqfranz a` to add
# the missing/misspelled/incorrect file to foo.zpaq later.
$ zpaqfranz a pippero1 pippero2 -o foo.zpaq
```

```bash
# Add pippero1 and pippero2 to foo.zpaq, which "magically" gets the .zpaq extension
# if it's not already present in the string passed to the `-o` output flag. For example,
# in Ruby:
#
#     extension = ".zpaq"
#     output_file+=extension unless output_file.end_with? extension
#
$ zpaqfranz a pippero1 pippero2 -o foo
```

then you can either error right away if any files are missing and avoid spending time compressing an incomplete archive, or you could delay errors and compress what you can and add any additional files afterwards. Delaying errors prevents a race condition if files/directories are moved, deleted, or renamed after zpaqfranz starts running (which can happen during a large backup, for example, on a read-write filesystem) but that's true *now* anyway unless zpaqfranz already handles that use case somehow. So, if you're not delaying errors, you could error out at any time.

### When Streaming to Standard Output, Redirections, or Pipes
What to do when the output is standard output or file redirection is less clear-cut. You have the same choices, but sending incomplete data down a long-running pipe or stream might not make a lot of sense, such as trying to stream zpaq-compressed data from stdout to `foo.zpaq` over an SSH connection, or pipe the stream to a process that doesn't really know how to read or append to .zpaq archives. In that case, what does zpaqfranz do now, and what should it do?

It's kind of a separate question that isn't directly related to the issue I originally raised, but answering your question made me wonder what the optimal behavior for streams with missing compression targets would be from a user's perspective. I'm not 100% sure what's correct, or how it works today, but the slowness of zpaq makes this a bigger issue for zpaqfranz than it does for lzo or gzip.

**Comment by todd-a-jacobs** [comment]
@fcorbelli I appreciate your detailed answer above. It seems like zpaqfranz is designed for a different use case than what I had expected, and your answers definitely make sense within that context. I appreciate you taking the time to explain the various reasons.

While I'd still like to see automatic extensions, I agree that it's not absolutely essential. It's mostly a user convenience for those of us who might be using it for use cases other than which it was originally designed. So, I'd still love it if you'd implement that piece of it in future, but you can close the issue for now if you like since my questions were resolved in the sense that they're largely out of scope for the intended use cases.

**Comment by fcorbelli** [comment]
I am working on a brand-new mode (the fasttxt), I'll embed some changes too
```
zpaqfranz a foo
```
_if file "./foo" or folder "./foo" does esists, create or update "./foo.zpaq" with the "./foo"_  
This should not broke scripts

**Comment by fcorbelli** [comment]
https://github.com/fcorbelli/zpaqfranz/releases/tag/58.5
