### ISSUE TITLE
New backup command acts weird

### ISSUE THREAD

**Issue by akumiszcza** [fcorbelli/zpaqfranz#58]
Hi! I'm trying the new backup command of zpaqfranz. I had a windows script to backup my obsidian data and repeat it every 10 minutes while the script is activated:

```
@chcp 1250
:begin
zpaqfranzhw a "\\foto\Volume2\backup\Obsidian_???.zpaq" %OneDrive%\Obsidian -longpath -hw -m3
zpaqfranzhw i "\\foto\Volume2\backup\Obsidian_???.zpaq"
timeout /t 600
goto begin
```

Now I made a new script with a new backup command instead:

```
@chcp 1250
:begin
zpaqfranzhw backup "\\foto\Volume2\backup\Obsidian.zpaq" %OneDrive%\Obsidian -longpath -hw -m4
zpaqfranzhw testbackup "\\foto\Volume2\backup\Obsidian.zpaq" -paranoid
zpaqfranzhw i "\\foto\Volume2\backup\Obsidian_????????.zpaq"
timeout /t 600
goto begin
```

Here is the part of results from the first script:
00000081 2023-06-02 08:58:06  +00000005 -00000000 ->                7.656
00000082 2023-06-02 09:08:06  +00000002 -00000000 ->                3.396
00000083 2023-06-02 09:17:05  +00000001 -00000000 ->                1.370

And here's from the second script:
00000002 2023-06-02 08:57:38  +00000670 -00000000 ->               51.140
00000003 2023-06-02 09:07:39  +00000670 -00000000 ->               47.967
00000004 2023-06-02 09:16:57  +00000670 -00000000 ->               46.336

(scripts ran at the same time)

As you can see, the backup command archives 670 files every time (which is even more than the number of files in this folder!), while only several files changed and it results in much bigger archives. Or maybe it is intended behaviour?

**Comment by fcorbelli** [comment]
Thanks for the report.
Onedrive has a 'strange' functioning, which is difficult to understand, and I never use it (it is the very first thing I disable)
Another user had pointed something similar out to me a while back.
I suggest - before going into it - to try another folder, e.g. from dropbox, to see if the behaviour is different.
You can get more information, on what happens, by using -debug and perhaps -outfiledilo.txt name
