### ISSUE TITLE
Can I use it to image windows install ?

### ISSUE THREAD

**Issue by SiddharthManthan** [fcorbelli/zpaqfranz#60]
Assuming I wish to restore manually, can I incrementally image the windows install ? Basically only copying the used blocks.

Plus what will the process of restoring look like ?

**Comment by fcorbelli** [comment]
You cannot get only the used blocks
You can use command to zero the free space

Then take all the sectors (deduplicated, compressed, encrypted)

To restore you must extract the raw image, then... open with 7z, for example, that "understand" NTFS based images (or some kind of raw image mounter, like osfmount or whatever)

From 7z gui you can easily extract every file or folder

I do this way

**Comment by SiddharthManthan** [comment]
Are there opensource other tools that allow me to create ntfs images ?


________________________________

**Comment by fcorbelli** [comment]
Some version of dd (ported on Windows)
Older zpaqfranz build retain a full dd.exe inside (!)  
look from this [first dd-enabled release](https://sourceforge.net/projects/zpaqfranz/files/56.2/)

**Comment by graphixillusion** [comment]
After the imaging of the c partition made with zpaq -image, will be possible to write it back to a clean partition using dd under a linux live env?

**Comment by fcorbelli** [comment]
You can try 😄 

Actually it is more backup mechanism for "strange" files than image for restoring. 
As soon as I find some time I will do some experiments with it

**Comment by graphixillusion** [comment]
Or another solution would be  mount img with osfmount, then capture the image with dism and apply it back with dism using the official way.
