### ISSUE TITLE
[Wiki] Clone fails because invalid chars in titles

### ISSUE THREAD

**Issue by cocoon** [fcorbelli/zpaqfranz#67]
Nice to have the great documentation already in the wiki!

One small problem:
cloning the wiki fails (on Windows) because the titles contain ":" and this is invalid for filenames.

Would be great if we could get rid of invalid chars so that cloning succeeds:

```
git clone https://github.com/fcorbelli/zpaqfranz.wiki.git
```

**Comment by fcorbelli** [comment]
WOW!
At least ONE user in the world who reads the Wiki! :-)

I will try to improve and update it

**Comment by fcorbelli** [comment]
Fixed. Maybe I'll update some more pages...
```
Z:\pgit\bin>git clone https://github.com/fcorbelli/zpaqfranz.wiki.git
Cloning into 'zpaqfranz.wiki'...
remote: Enumerating objects: 905, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 905 (delta 20), reused 0 (delta 0), pack-reused 865
Receiving objects:  94% (851/905)
Receiving objects: 100% (905/905), 152.70 KiB | 1.38 MiB/s, done.
Resolving deltas: 100% (520/520), done.
```

**Comment by cocoon** [comment]
Oh wow that was quick!

Of course, I really appreciate the documentation and especially examples that show the differences!

Man thanks for that, I know taking time for documentation might fall behind if you could instead work on fixing or improving code, but it really helps.

**Comment by fcorbelli** [comment]
Unfortunately, the documentation is hardly read by anyone.
So I don't put much effort into it

**Comment by fcorbelli** [comment]
Some update posted on wiki (work in progress...)

If you like zpaqfranz, please subscribe... (kidding)... 

_please put a review on https://sourceforge.net/projects/zpaqfranz/reviews and stick a star on github :-)_

**Comment by cocoon** [comment]
Wonderful, many thanks for your support!

Review and Star done ;)


(I missed that Reviews are not well formatted on SF ... )

But here again, how and why I plan to use zpaqfranz.



**How I plan to use it**

All this backup process is just for my father to backup important files additionally over VPN to a Fileshare on my Router and make it easier for him.

Currently I use Kopia directly for it but it has problems to backup to NAS fileshares that do not perfectly work with file times, as they heavily rely on it, maintenance / cleanup / dedup tasks cannot run without it.
zpaqfranz stores all internally and simply appends data, like in containers, so I would have expected something like this for Kopia etc ... but ... no, would just make it independent to the outer filesystem.

Another small problem is that the official WireGuard sometimes connects to late for it, or where manual reconnection is needed.

So I plan to change the backup like this:

- Kopia stores backups locally (make it happy with normal NTFS)

Then for remote backup I plan now to integrate zpaqfranz it in an own app that:
- establishes a VPN connection (Wireguard)
- connects the Fileshare
- backup the Kopia repository with zpaqfranz to the Fileshare
- disconnect VPN

That's it.



**IDEAS**

By the way, while working on it I had some small ideas, I just leave them here (not fully thought through ...):

- zpaqfranz could use backup-job-config-files instead of appending all parameters, so one could configure one or more backup kobs in (json) files and so the command would get shortened to just:
`zpaqfranz myjobfile.json`

- zpaqfranz could additionally use something like backup profiles with rules (could be in the backupjobconfig file or multiple extra files for different rules), like:
  - after backup file size is 1.8GB use new one and increase number in filename
  - after 1000 backups use new file

I had the idea to get the possibility to get the output formatted in different formats, like json, but you already added last time a new formatting for output.
That would make it easier to parse it in other programs, like info about archive, backup outcome, and sorting. For example I currently parse it into custom class objects and can just show last 5 snapshots and reverse the order to show latest on top.

![archive_infos](https://github.com/fcorbelli/zpaqfranz/assets/1071741/2a46d0e7-e3cb-4030-82ef-9bda73c1a2fc)


A (REST) API Service for it would be overkill I think ^^

I don't know if anything of this makes sense.

**Comment by fcorbelli** [comment]
> All this backup process is just for my father to backup important files additionally over VPN to a Fileshare on my Router and make it easier for him (...)

Typical use of zpaqfranz is with rsync-over-ssh with --append  
Often with this one https://www.hetzner.com/storage/storage-box

> **IDEAS**
> * zpaqfranz could use backup-job-config-files instead of appending all parameters, so one could configure one or more backup kobs in (json) files and so the command would get shortened to just:
>   `zpaqfranz myjobfile.json`  

It's not very likely, because I don't think I want to turn zpaqfranz into something extremely complicated in default use.


> * zpaqfranz could additionally use something like backup profiles with rules (could be in the backupjobconfig file or multiple extra files for different rules), like:
>   
>   * after backup file size is 1.8GB use new one and increase number in filename  

There is already something like that
```
+ : -freeze kajo  If current archive size > maxsize, move to kajo folder
```
I can implement a "rename" strategy, but not very good (rsync with a diffent name will start a new upload)
>   * after 1000 backups use new file  

If the files are very deduplicated the space occupied is minimal, I might do it more for the number of versions.
If you have stored 1000 versions, start with a new archive
I like this one

> I had the idea to get the possibility to get the output formatted in different formats, like json, but you already added last time a new formatting for output. That would make it easier to parse it in other programs (...)  

I have a program for this, too :)
It is zpaqlist, part of PAKKA  
https://github.com/fcorbelli/zpaqlist

> A (REST) API Service for it would be overkill I think ^^
> 
> I don't know if anything of this makes sense.

I think I'm going to improve the archiving function ... of the archives.

Thank you for any suggestions, they are critical to improving the program

**Comment by cocoon** [comment]
And I think closing this one here, as the initial problem is solved already, no need to keep ir open.
