### ISSUE TITLE
Request: Wiki Update

### ISSUE THREAD

**Issue by EpicGazel** [fcorbelli/zpaqfranz#87]
I made a utility to make browsing the contents of a zpaq a bit easier: https://github.com/EpicGazel/ZpaqTreeView
![ZpaqTreeViewScreenshot](https://github.com/fcorbelli/zpaqfranz/assets/20029624/43b67acb-d80f-4939-8d84-ed1f0616d7ad)

I created a basic wiki page for this: https://github.com/EpicGazel/zpaqfranz/wiki/ZpaqTreeView-Windows-GUI
This may be helpful to other users. No worries if it does not match the wiki's intended purpose or if there's any other reason it cannot be added.

**Comment by fcorbelli** [comment]
Putted on the readme, more visible
