### ISSUE TITLE
Missing option to run BAT after making VSS snapshot.

### ISSUE THREAD

**Issue by mirogeorg** [fcorbelli/zpaqfranz#9]
Many backup apps have option to run scripts BEFORE and AFTER VSS snapshot.
Example use case is to stop db, make VSS, then start db and after that to continue with backup process.
I miss VSS AFTER script in ZPAQFRANZ.

Example in Drive Snapshot:
--exec:"NET START ORACLE" 
--exec:"RestartExchange.bat"

for use with the internal driver: after snapshot creation (just a few seconds after starting the backup), you can execute external command. has to be the last command on command line!

**Comment by fcorbelli** [comment]
yes, you are right.
I will implement
